### ISSUE TITLE
Error with wp_insert_post not caught, item never gets created and can never synced (if required data is missing but not in such a way that it returns a WP_Error)

### ISSUE THREAD

**Issue by pattyok** [MinnPost/object-sync-for-salesforce#103]
If you do a wp_insert_post with an item that is missing content in the 'post_title' or 'post_content' fields, wordpress does not throw an error, but returns '0', in the plugin this then gets assigned as the mapped wordpress_id in the wp_object_sync_sf_object_map table so on subsequent updates it registers that the item exists and tries to do an update on the wordpress post with the id of '0' which will fail as it doesn't exist. 

There are several places to fix but most importantly - 'post_title' and 'post_content' should always be passed, and the mapping should never get saved if the wp_insert_post function returns '0'.

**Comment by jonathanstegall** [comment]
I'll check into this issue. Always accepting pull requests, as well.

**Comment by pattyok** [comment]
After some investigation, I think the simplest fix is to pass a second
parameter of "true" to wp_insert_post and wp_update_post which will return
an error if there is an error . I'll test and try and put together a pull
request this week...
