### ISSUE TITLE
Admin: front end stuff

### ISSUE THREAD

**Issue by jonathanstegall** [MinnPost/object-sync-for-salesforce#11]
We need a few things that are currently minor:
1. CSS that fits the markup (and/or modifications to the markup) for the admin
2. Form sanitization/validation (client and/or server side)
3. Form error messages

**Comment by jonathanstegall** [comment]
List of admin pages:

1. [Settings](/wp-admin/options-general.php?page=salesforce-api-admin&tab=settings)

**Comment by jonathanstegall** [comment]
I feel okay about the styling, at least for a v1 release. But the validation is something that needs further investigation. It's unclear to me how much we could just use the sanitize methods, and how much we need to do other stuff.

**Comment by jonathanstegall** [comment]
For sanitizing, I tried this:

`register_setting( $page, $id, array( $this, $validate ) );`

```
// this method does not fire an error if it is private, but also doesn't work
public function validate_text( $input ) {

    $output = '';

    if ( isset( $input ) && !is_array( $input ) ) {
        $output = strip_tags( stripslashes( $input ) );
    }

    if ( isset( $input ) && is_array( $input ) ) {
        
        foreach( $input as $key => $value ) {
            if ( isset( $input[$key] ) ) {
                $output[$key] = strip_tags( stripslashes( $input[ $key ] ) );
            }
        }
        
    }

    // Return the array processing any additional functions filtered by this action
    return apply_filters( array( $this, 'validate_text' ), $output, $input );
}
```

It kind of works, but it throws some errors that seem to be impossible to debug without generating a 14 gig Apache error log.

**Comment by jonathanstegall** [comment]
The error for the current validation method is this:

`[08-Dec-2016 20:31:56 UTC] PHP Warning:  Illegal offset type in isset or empty in /wp-includes/plugin.php on line 188`

**Comment by jonathanstegall** [comment]
That error is addressed in 77738d29fa7eb13cada9fab3caa44756ec315a66

**Comment by jonathanstegall** [comment]
[https://handbuilt.co/tip/securing-input/](https://handbuilt.co/tip/securing-input/)

**Comment by rclations** [comment]
I think i've covered everything remaining from your checklist above re: validation and this is ready to be closed
