### ISSUE TITLE
Meta Information

### ISSUE THREAD

**Issue by prowp** [MinnPost/object-sync-for-salesforce#110]
I'm using this to do an integration with WooCommerce, and the meta fields aren't showing up as options. I looked at the code, and it's not clear to me why those fields aren't there. 

I DID fix this with a filter, but I wanted to raise it as an issue as it could possibly be an indicator of some problem, or it could just be something odd in WC somewhere.

**Comment by jonathanstegall** [comment]
@prowp Thanks for the issue. While I haven't tested this plugin with WC myself, I do know that there are lots of methods for doing meta fields that might be what WC is doing. For this plugin we basically only show the fields that are retrievable by these methods:

1. `wp_get_attachment_metadata`
2. `get_user_meta`
3. `get_post_meta`
4. `get_term_meta` (which does support a lot of "custom" post styles, but certainly not all ways of doing them)
5. `get_comment_meta`

I am familiar with WC but I haven't used it enough to know how it creates its database structures, but I have noticed that it creates a lot of custom tables. My gut says it probably uses something that is not the default meta methods as well, and that would explain why it doesn't show up.

I haven't really thought a lot about bundling things like that, which aren't WordPress standards but might as well be, into this plugin. I would be happy to link to any plugin that uses the filters to create good WC support, though, even if such a thing doesn't get bundled into this plugin. I am inclined to think it's better to keep it separate, but I'd be open to conversation around that.

**Comment by prowp** [comment]
Thank you for the feedback, I will do some further testing. The information is strictly meta information, nothing from a custom table. I have a ways to go on this project, so I will dive in more, and if I find something that makes sense to add, I do a PR.

I will say that the hooks made it easy to make it work out the way I wanted. This is not a blocking issue for me, or anything like that, i just wanted to point it out.

**Comment by jonathanstegall** [comment]
@prowp great let me know. I did see this info from WC: https://github.com/woocommerce/woocommerce/wiki/Database-Description. It indicates that there are custom tables for some metadata (I see woocommerce_order_itemmeta and woocommerce_payment_tokenmeta in there). Presumably these tables would not show up without the hooks, but other default metadata should.

But for sure, if you find that there's a problem I'd be happy to take a PR later. I'll leave this issue open for now.

**Comment by jonathanstegall** [comment]
Presumably this issue is out of scope for the core of this plugin, as it relates to other plugin data storage methods. Going to close it for now.

**Comment by prowp** [comment]
Yes, this not specifically a problem. Just more of a note (for anyone) that if you are starting with a clean site, you may have to initially enter any custom meta keys via a filter to get them populating as there is no way to enter keys that don't exist yet.

Thanks for the follow up.

**Comment by jonathanstegall** [comment]
@prowp oh hey, we released an update a while ago that provides some basic support for WooCommerce content type/meta fields. I expect there is functionality it does not support and we'd have to have an add-on to do more than it does, but at least orders are now supported.

Also I'm tracking your last note about getting meta keys to populate before they have data. I am not sure that there'll be a viable way to fix it, but I at least want to keep it in mind. #119 is the issue.
