### ISSUE TITLE
Mismatched Post Type

### ISSUE THREAD

**Issue by prowp** [MinnPost/object-sync-for-salesforce#111]
I have an oddball problem and I just want a hint on the best way to troubleshoot it.

I deactivated and reactivated on the plugin on a dev site, and lost my field mapping and objects, which isn't a problem, but should be noted.

I deleted the old test objects, checked to make sure the 2 custom tables where empty, and recreated my field map. 

When I started to get new sync items, they went to the wrong post type.  They are doing this consistently now. I've manually checked the data in both tables which has the correct post type showing, so I'm a little stumped on why it's defaulting to post when a sync happens. What is the best way for me to troubleshoot this issue? It's as if no post type is being passed to the insert. If I manually change the post type in the db on the created post, the updates process with no issue.

**Comment by prowp** [comment]
I should mention that error logging is running and there are no errors showing up.

**Comment by jonathanstegall** [comment]
@prowp this is an odd issue. Maybe you can investigate these things:

1. What is in the cache for the plugin's settings? Currently it does not get cleared when the plugin is deactivated (this is an issue, of course, but it is complicated with all the various object caching methods).
2. Did anything change in either the WordPress or Salesforce configurations?
3. What would have been the correct post type, and what is the actual post type that is being incorrectly synced?
4. I see you say there are no error logs showing up - does it show any success messages in the logs as well? I'd be interested to see if it thinks it is working correctly.

Also, I see you saying that both tables have the correct post type. What data gets put into the `wp_object_sync_sf_object_map` folder? Does the plugin assume that the data type is what it's supposed to be in both directions, or does it realize that the wrong post type is being modified?

**Comment by prowp** [comment]
No change in the configuration other than rebuilding and expanding the field map. The post type is product, and it's coming out as a post. 

So, I played with toggling settings and came up with a specific situation. I was testing the upsert function mapping a post meta field as a salesforce object id, and marking it for upsert, I'm not really using it this way, I was just looking at the functionality. This specific change was causing a post to be created instead of a product. I turned on success logging and for both the correct post types being created and the wrong ones, it comes out as product in the log.

This could be me just misunderstanding how to use this, and I don't need it to it's not a blocker for me. I just wanted to report on it, because the behavior is strange. If I'm not using any type of upsert, it seems fine.

**Comment by jonathanstegall** [comment]
@prowp Thanks, that makes sense. Upsert should not do that, of course, but that gives me something to track down. I think I can do that and get a fix out.

**Comment by jonathanstegall** [comment]
I've released an update to the WordPress plugin and also to the repo here, and I believe it fixes this issue. It's a relatively small change and I've tested it locally, but I can leave this open for a few days in case you want to try it out as well.

**Comment by jonathanstegall** [comment]
I'm going to assume the 844593717f7c4512085990026f8f13c28e1b94de commit has successfully solved this issue.

**Comment by prowp** [comment]
Yes, sorry for taking so long. This issue seems fixed. Thank you for fixing it so fast, I didn't expect that.
