### ISSUE TITLE
Object_Sync_Sf_Salesforce_Pull fatal memory error while queueing large sync volumes

### ISSUE THREAD

**Issue by charmoney** [MinnPost/object-sync-for-salesforce#113]
Client recently ran a SF batch process, updating the last modified date of several thousand objects. The issue came to our attention several days later, when the site completely crashed.

The `Object_Sync_Sf_Salesforce_Pull->get_updated_records()` function is not written in a memory safe manner. The function will keep pulling back additional pages from SF, creating objects, and queueing them. If the function runs out of memory and fails, the last sync date used is not updated. As a result, the next time the cron executes, it re-queries the same content and re-queues the same records until crashing again. And again. And again.

Over time the WP options table bloats, causing site slowdowns and in our case a MySQL corruption crash of the table after exceeding 6 GB, including over 20,000 `salesforce_pull_batch_%` options.

At a minimum, consider setting the `'object_sync_for_salesforce_pull_last_sync_' . $type` option periodically during the queueing process. (Possibly to the last queried date field value after the `foreach ( $response['records'] as $result )` blocks, which would limit the number of repeat queued items to a single page of SF records.)

There are probably more robust solutions as well, including handling the queueing process with the same rigor and care as the queue handling process.

This is related to #29 but seemed to be worth a dedicated issue.

**Comment by jonathanstegall** [comment]
I also was curious about whether we should have a max queue size. #40 mentions how the Drupal module handles that. I expect that would keep this from happening as well. Drupal has a nice queue system built in, though, so I'm not sure it would be as simple to put that in there in our case. You may have a better solution when you mention changing the last_sync value.

**Comment by charmoney** [comment]
@jonathanstegall I'm working through recovery right now.  I think I found the source of the memory leak and crash in the function.

Records are queued by executing 

```
$this->schedule->push_to_queue( $data );
$this->schedule->save()->dispatch();
```

Which does not queue an individual item, as you'd expect. Instead, it appends the item to the current queue and adds that now-larger queue to the options table. E.g. queue item 1 has item A; queue item 2 has items A & B; queue item 3 has items A, B, and C; and so on until PHP runs out of memory or the MySQL table crashes.

In our current situation, the MySQL tables goes corrupt when inserting the option with 140 items for processing. The option_value for the 139 record queue is over 1.57GB.

I'm going to take a look at options for modifying the code locally to get through this particular outage. If I come up with a reasonable option, I'll submit a PR.

**Comment by charmoney** [comment]
Created an imperfect pull request that helps mitigate the issue. Memory use and DB size are both significantly reduced by avoiding the queue aggregation I described.

I traded off a performance hit to update the sync pull timestamp after every successfully queued record. When the fatal error does hit, at least the pull doesn't get stuck re-queueing the same records in perpetuity. Eventually the pulls churn through all available records and move on to processing.

I'm sure there is a more bulletproof solution to remove any chance at a fatal error. This was enough of a mitigation to hotfix onto our live site and successfully process the massive backlog of records I described.

**Comment by jonathanstegall** [comment]
Many thanks for this. It looks good. I'm inclined to think that I'll need to investigate whether this background processing class is viable sooner rather than later. I have an issue for it at #112. I can leave this one open for a bit, so we can make sure that this specific issue is resolved, and assuming it is we can close it.

**Comment by charmoney** [comment]
Agreed. I think moving away from the background processing library could be the more robust option.

A small recommendation that may be a better fit for #112. From other integration syncing projects, I'm a fan of having two tiered queues:

First, check the count of available items. Then queue tasks to pull and process each page of content. Those tasks in turn queue record level tasks. The record level task, finally, is the one that actually does the work.

Using this approach, each individual task (getting a count, handling a single page, or processing a single record) is reasonably sure to be small enough to complete.

**Comment by jonathanstegall** [comment]
@charmoney I wonder if you'd be willing to help test what I think is a good solution for this issue. I've put in the [Action Scheduler](https://github.com/Prospress/action-scheduler) library, as I think it achieves what you mention above.

There's a pull request, #195, with this happening. I'm still trying to do a bit of testing before release to see that it works ok when users upgrade to this version, but I'd also love another pair of eyes if you could spare it.
