### ISSUE TITLE
Object_Sync_Sf_WordPress->post_create() does not support content fields for a modified SF object

### ISSUE THREAD

**Issue by charmoney** [MinnPost/object-sync-for-salesforce#115]
`Object_Sync_Sf_WordPress->post_create()` only supports newly created SF Objects content fields by explicitly checking for `'wp_insert_post' === $value['method_modify']` to prepare the insert post call.

Create and Upsert logic both invoke post_create whenever a WordPress post does not exist yet. If the SF Object was modified, the method_modify will be `wp_update_post` instead.

In our case, only a subset of SF Objects are being synced. When the SF Object meets the criteria at the time of creation, the sync works and the post record is created in WP perfectly. When the SF Object is modified to meet the criteria some time later, the sync creates a draft post record without any title, author, or content. Interestingly, the post is created successfully, which means the update_post_meta params all work correctly.

Reproduction steps:

1. Create a new field mapping to a post or custom post type, setting multiple `wp_insert_post()`/`wp_update_post()` values like post title, content, excerpt, author, and status.
1. Filter the pull allowed to disallow all pulls.
`add_filter( 'object_sync_for_salesforce_pull_object_allowed', '__return_false', 10, 5 );`
1. Create a new SF object (Object A)
1. Perform a pull
1. Create a new SF object (Object B)
1. Remove the disallow filter
1. Perform a pull
1. Result: Object A is created as a draft post with blank content, title, and other core fields. Object B is created fully and correctly.
1. Modify Object A in SF
1. Perform a pull
1. Result: Object A is now correct in WordPress

If this is intentional, I believe we can work around it by using the `object_sync_for_salesforce_pull_params_modify` filter to change all of the updates to inserts as needed. If this isn't expected behavior, I'll be submitting a small pull request to resolve it.

**Comment by jonathanstegall** [comment]
I can see that this is problematic. I am not entirely sure what the most consistent resolution would be, though.

>>>
- Create a new SF object (Object A)
- Perform a pull
- Create a new SF object (Object B)
- Remove the disallow filter
- Perform a pull
- Result: Object A is created as a draft post with blank content, title, and other core fields. Object B is created fully and correctly.

I think that is not ideal, either way. Either Object A should be ignored, or as your pull request indicates, both A and B should be fully created.

I am wondering if I need to try other object types as well, and see what happens with them. I am a little nervous about the plugin, for example, allowing posts to connect differently with the plugin than users.

**Comment by charmoney** [comment]
Your wariness certainly makes sense.

As a workaround in case anyone else is running into this issue, the pull params filter is easy to use to mitigate the issue:

```
/**
 * Modify SF pull parameters
 */
function my_sf_pull_params_modify( $params, $mapping, $object, $sf_sync_trigger, $false, $is_new ) {
	// Set the method_modify of content params to wp_insert_post for new records so post_create works
	if ( $is_new ) {
		foreach ($params as $param_key => $param_value) {
			if ( 'wp_update_post' === $param_value['method_modify'] ) {
				$params[$param_key]['method_modify'] = 'wp_insert_post';
			}
		}
	}
	return $params;
}
add_filter( 'object_sync_for_salesforce_pull_params_modify', 'my_sf_pull_params_modify', 10, 6 );
```

**Comment by jonathanstegall** [comment]
I checked this with the `user` object, and here was the result:

1. Create a new SF object (Object A)
2. Perform a pull
3. Create a new SF object (Object B)
4. Remove the disallow filter
5. Perform a pull
6. Object A is skipped - no user is created. Object B is created fully and correctly.

I am inclined to think the `post` should perform this way as well, unless the workaround above is being used. I'll plan to work on this, and to make sure it doesn't break the workaround.

**Comment by charmoney** [comment]
Really? That's odd. We're syncing SF Account objects with an email address
to WP Users. People routinely add email addresses to existing Account
records, causing them to meet the pull allowed criteria long after
creation. The WP User for the newly allowed modified Account is always
created during the next pull. In that example, both Object A & Object B are
created fully and completely in my experience.

**Comment by jonathanstegall** [comment]
I do see that it does create Object A if, after it is initially totally skipped and Object B is created, I go back and update Object A. I expect that is what you see when you update the Account records?

**Comment by charmoney** [comment]
That may well be the case. Creating new WP User records from modified (not
newly created) SF Accounts worked right away. Since the user records never
ran into the insert issues we saw with posts, I never looked into the
precise processing steps in any detail.

**Comment by jonathanstegall** [comment]
Yes. I think that is how it should behave. With posts, I think it should skip Object A, create Object B, but then if it is updated later, it should create a new, correctly filled, post for Object A.

I am not sure why it creates the blank entry, but I think that is the fix I need to investigate.

**Comment by jonathanstegall** [comment]
I made another pull request that I think will fix this. I do need to test it more though, if you'd also want to test it. https://github.com/MinnPost/object-sync-for-salesforce/pull/117

**Comment by charmoney** [comment]
Thanks, I understand what you're saying now.

I'm not sure if pull request #117 will resolve the issue.

The blank entry is because the later updated Object A method_update values
are wp_update_post. But the post_create function only looks for
method_update values of wp_insert_post, which is only the case for newly
created SF Objects (rather than the updated SF Object A).

I don't see how this pull request will change the post_create function
being called with params whose method_update values are intended for
post_update.

**Comment by jonathanstegall** [comment]
You're right, that didn't work. It still created the blank entry. I've added some more. I think it achieves the same goal you had, but it behaves more like `user`: it checks to see if the data exists, using `_exists` methods, and if it does it does not create anything, but if it doesn't it creates a new row.

I've tested this with the core problem on this issue. It skips Object A the first time, then creates Object B, then if Object A gets modified it creates a new `post` for Object A.

I probably need to do more testing before merging this.

**Comment by jonathanstegall** [comment]
Also, while I'm thinking about it, would you like to be added to the list of contributors on this plugin in the WordPress plugin directory? If so, what is your WP username?

**Comment by charmoney** [comment]
I worry that the logic currently in pull request #117 will cause meta values not to load for newly created posts.  I just added a more general logic technique to #116 that could be incorporated into #117 and used for attachments & comments.

It switches from checking for strings like wp_insert_post directly to instead looking for any content_method fields according to that object's structure.

My WP.org username is "harmoney" and thanks!

**Comment by jonathanstegall** [comment]
I've merged that #116 logic and applied it to the other object types.

I haven't tested yet, but it seems like this would fix the issue so we don't have to do `post_exist` checks and such. Is that your understanding?

I'm still inclined to maybe bring over the fix that moves the `pull_allowed` flag earlier in the process, but that is of course unrelated to this issue.

**Comment by charmoney** [comment]
Yes, I believe the logic should resolve the potential for this issue across
all object types.

I also agree that the $pull_allowed flag would be good to check earlier,
though as you said it isn't directly related.

**Comment by jonathanstegall** [comment]
I'm going to release an update now. As far as my testing indicates, this is fixed, so I'll close it. We can reopen if it proves to be unresolved.
