### ISSUE TITLE
Date fields coming from Salesforce can cause WordPress insert/update to fail

### ISSUE THREAD

**Issue by jonathanstegall** [MinnPost/object-sync-for-salesforce#142]
### Expected behavior

If you map date fields, the plugin should be aware that the field's value needs to be formatted as a date. I believe it already does this if it is being sent to Salesforce. In cases where it does fail, it should create an error log entry.

### Actual behavior

If the date is being saved in WordPress, it can silently fail.

### Steps to reproduce behavior

1. Map two objects, and make sure one of the WordPress fields is a date field.
2. Insert/update the data in Salesforce.

**Comment by jonathanstegall** [comment]
To look into:

We have this code in `salesforce_mapping.php`:

```
if ( isset( $salesforce_field_type ) ) {
	// Is the Salesforce field a date, and is the WordPress value a valid date?
	// According to https://salesforce.stackexchange.com/questions/57032/date-format-with-salesforce-rest-api
	if ( in_array( $salesforce_field_type, $this->date_types_from_salesforce ) ) {
		if ( false !== strtotime( $object[ $wordpress_field ] ) ) {
			$timestamp = strtotime( $object[ $wordpress_field ] );
		} else {
			$timestamp = $object[ $wordpress_field ];
		}
		if ( 'datetime' === $salesforce_field_type ) {
			$object[ $wordpress_field ] = date_i18n( 'c', $timestamp );
		} else {
			$object[ $wordpress_field ] = date_i18n( 'Y-m-d', $timestamp );
		}
	}

	// Boolean SF fields only want real boolean values. NULL is also not allowed.
	if ( 'boolean' === $salesforce_field_type ) {
		$object[ $wordpress_field ] = (bool) $object[ $wordpress_field ];
	}
}
```

I feel like this should be fixing the mentioned issue, but apparently at least in some cases it does not.

**Comment by jonathanstegall** [comment]
This is the reported error (on updating a post)

```
The content array is this:
array(4) {
	["ID"]=> string(4) "7766"
	["post_date"]=> string(16) "January 24, 2018"
	["post_modified"]=> string(16) "January 29, 2018"
	["post_type"]=> string(7) "product"
}

The error that gets kicked back is this:
object(WP_Error)#3504 (2) {
	["errors"]=> array(1) {
		["invalid_date"]=> array(1) {
			[0]=> string(13) "Invalid date."
		}
	}
	["error_data"]=>
		array(0) {
		}
}
```

**Comment by jonathanstegall** [comment]
The issue is that the parameter mapping does not always know how to format the date field. I think the best solution is to track all of the core WordPress date fields and the formats that WordPress expects them to have, and send the dates in that format.

Presumably if users are using a plugin with other date formats (ie CMB2 or whatever) they can have that plugin either use the same format as the core fields, or switch it with a hook.

**Comment by jonathanstegall** [comment]
However there's a different issue here in which the error logging is not happening correctly. I don't understand this part, as my install does return errors.

**Comment by prowp** [comment]
Not sure why it would be different. What I was seeing is that the cron run would start, and I could see the timestamp in the object table saying that the item was updated, but it was not.

The customization that I have is just an automation hook that runs after the pull, that just sets a meta field for a larger automation to run that categorizes based on the updated data. Error logging showed that the action after the pull was never triggered during these failures.

I did have multiple fieldmaps mapped to each post, which I figured out after this was working, that only the first one runs, so I've reduced it back to one large one. I am using async processing for the records. 

To isolate, I had to insert a bunch of manual error logging points to find the fail. The site is on WPEngine, if that matters. 

BTW, is there anywhere we can donate towards all the time you spent on this plugin?

**Comment by jonathanstegall** [comment]
I think I've got a fix for this (in the commit above). It does this:

1. When you create a fieldmap, it checks the object's WordPress table for field types (so wp_posts, wp_users, wp_terms). It then saves the field type with that field in the database. It already does this for Salesforce.
2. When a Salesforce event happens, if there is a WordPress field type and it is `datetime`, it formats the value as a MySQL datetime before inserting/updating it.

I don't have any changes for the error logging at this time, at least. I get error log entries in WordPress (in the Logs content type) that show the same errors you mentioned earlier.

But the fix appears to work well, in the testing I've done so far, but probably need to do a bit more before releasing it. In any case once it is released, it won't start happening until the plugin cache is cleared.

As you say, the plugin does only support one fieldmap for each. #135 is a pending issue for this, but it is rather complicated and certainly there's not an ETA for that yet.

Also thanks so much for asking about donating. MinnPost is a nonprofit, and certainly welcomes any donations to further support the plugin! You can do that at https://www.minnpost.com/support/?campaign=7010G0000012fXGQAY.

**Comment by prowp** [comment]
Thank you so much for your responsiveness! The patch on my end was simply an interception of those date fields and a quick reformatting before the call to wp_update_post. I'm just glad to have gotten it figured out! I'm running the plugin on a rather large client site with a good amount of data to sync, it's recently launched, so trying to stay on top of any issues. Your help is much appreciated!
