### ISSUE TITLE
New WordPress Record not syncing all mapped fields only edit syncs all mapped fields

### ISSUE THREAD

**Issue by NexusPrime1** [MinnPost/object-sync-for-salesforce#144]
Hi

I have mapped WP "User" to a custom object in SF. When a user is created / edited in WP the fields are to be synced to the SF object. 

However...

When a user is created in WP only the WP user ID, Name and Surname fields (which are mapped) are synced to the SF object the rest of the mapped fields are not synced. If however I edit and save the WP user or click the Push to SF button it syncs the rest of the fields to SF.

I have tried different  settings and just end up at the same issue. 

Please help me I have lost many hours of sleep.

**Comment by jonathanstegall** [comment]
@NexusPrime1 I haven't seen this issue before.

Some ideas:
- Have you checked the logs, both those created by the plugin and those on the server itself?
- Have you cleared the plugin's data cache?
- Does it behave differently if you use asynchronous vs synchronous syncing?
- What happens if you try to sync the data from Salesforce to WordPress? Does it have the same issue?
- What version of PHP and WordPress are you running?
- What are the other fields you are trying to sync? Are they standard user meta fields, or are they created by a plugin (which one, if so)?
- How many WordPress users have you noticed this issue with? Does it behave the same if you try with another user with different data?

**Comment by NexusPrime1** [comment]
Hi Jonathan


Thank you for your quick reply.


  *   Have you checked the logs, both those created by the plugin and those on the server itself? - WP Log is "Success Create SF object" (Not sure where server logs are)
  *   Have you cleared the plugin's data cache? - Yes
  *   Does it behave differently if you use asynchronous vs synchronous syncing? - No same results
  *   What happens if you try to sync the data from Salesforce to WordPress? Does it have the same issue? - Create in SF All field data sync perfectly when scheduled
  *   What version of PHP and WordPress are you running? - PHP Version 5.6.33-0+deb8u1
  *   What are the other fields you are trying to sync? Are they standard user meta fields, or are they created by a plugin (which one, if so)? -  The fields that don't sync on WP create are created in a Plugin - Buddy Forms
  *   How many WordPress users have you noticed this issue with? Does it behave the same if you try with another user with different data? - Happens with every new user created in WP

Did some more testing and it appears that if I create the user in WP and have schedule set for both WP to SF and SF to WP sync and then change something in SF it does not sync. However if I edit and save in WP or push the Push to SF button and then go to SF and change a field it will sync when scheduled.

I am lost with this one, if memory serves me correctly I do remember this working on WP create before and then when I tried it again a week later it had stopped working.

Thank you so much for all your help.

Regards

________________________________

**Comment by jonathanstegall** [comment]
@NexusPrime1 I'm not familiar with Buddy Forms. It's very likely that is the issue, though. This plugin supports core WordPress methods of doing meta fields, but many plugins have their own way of doing things.

There are abundant hooks available in this plugin; you could use them to write an extension plugin that would probably support Buddy Forms. There's documentation about the developer hooks here: https://github.com/MinnPost/object-sync-for-salesforce/blob/master/docs/all-developer-hooks.md

**Comment by NexusPrime1** [comment]
Hi Jonathan

I think your correct in that my solution would be to use the hooks however in my testing just after registering a new user when I go to the users profile and either click on “Push to Salesforce”button or if I click on the “Update User” button it then pushes the rest of the fields through to Salesforce. So what I would like to do is hook in just after the standard fields have been pushed to Salesforce and either initiate a push or user update. Which hook is going to be one I need to use?

Regards
[SJ Sig1]
[SJ Sig2]<https://www.retailcapital.co.za/>

**Comment by jonathanstegall** [comment]
I think perhaps you should try the `object_sync_for_salesforce_push_success` action. It runs after a successful push.

Here's how this action works:

```
add_action( 'object_sync_for_salesforce_push_success', 'push_success', 10, 3 );
function push_success( $op, $response, $synced_object, $object_id ) {
    // do things if the save succeeded
    // $op is what the plugin did - create, update, upsert, delete
    // $response is what was returned by the $salesforce class. sfapi->response
    // $synced_object is an array like this:
    /*
    $synced_object = array(
        'wordpress_object' => $object,
        'mapping_object' => $mapping_object,
        'queue_item' => false,
        'mapping' => $mapping,
    );
    */
    // $object_id is the salesforce object id
}
```

While as I said, we don't provide support for plugins that work in a non-standard way, if you build something that works with Buddy Forms I'm happy to link to it at https://github.com/MinnPost/object-sync-for-salesforce/blob/master/docs/example-extending-plugins.md.

I'm going to go ahead and close this issue for now, though, as it doesn't seem to be related to this plugin.
