### ISSUE TITLE
Prematch and Key are ignored for fields not marked as updateable

### ISSUE THREAD

**Issue by johnpbloch** [MinnPost/object-sync-for-salesforce#157]
### Expected behavior
When pushing a new record (object for which there is no object mapping row in the database, not necessarily a new post/term/user), if a field is marked as a prematch, and/or Salesforce key, the `$mapping` array should contain `prematch` and/or `key` arrays, even if that field is not updateable.

### Actual behavior
When building the `$mapping` array, if the field is not updateable, it will not be added as the `prematch` or `key` field.

### Steps to reproduce behavior
- Create a new Contact in Salesforce
- Create a new user in WordPress
- Add a meta value to that user containing the Contact ID (field name: `Id`) from the new user in Salesforce
- Create a mapping for Users to Contacts with that meta key mapping to Contact ID, and some other fields mapped as well (just to be able to see the results), with at least WordPress update as a trigger. Make sure the meta->Contact ID fieldmap is marked as prematch and/or key and no other fields are marked as prematch or key
- Change the user's name

Instead of using the meta to perform an upsert on the existing and correct Contact record, it will create a new Contact in Salesforce.

I went through the code and discovered that the problem arises in `object-sync-for-salesforce/classes/salesforce_mapping.php`, `Object_Sync_Sf_Mapping::map_params()`. In v1.3.2, at line 717, fields that aren't marked as updateable in Salesforce get skipped, but fields don't get checked for being marked as keys until line 756 or as prematch until line 768 (both of which are later in the same loop as the updateable check at 717).

The workaround is pretty simple: I just use the `object_sync_for_salesforce_find_sf_object_match` filter to manually set the `$salesforce_id` value, so this isn't super urgent, it would just be nice for prematch and key to work as expected in future versions.

Thanks for all your work on this plugin. Have a nice day!

**Comment by jonathanstegall** [comment]
Thanks for reporting this. This certainly should be as you say, thinking about it. I'll investigate a fix for next small release.
