### ISSUE TITLE
Which hook to manually trigger a push?

### ISSUE THREAD

**Issue by social-ink** [MinnPost/object-sync-for-salesforce#163]
We have a custom user dashboard where the user updates metadata. It doesn't seem like a push is being triggered after using update_user_meta from code (whereas from wp-admin, updating a user record does trigger a push), so is there a manual hook or action we can call? Eg:

```
update_user_meta($user_id, 'favorite_color', 'blue');
echo 'updated!'
do_salesforce_push();  //get the new favorite color into SF
```

**Comment by social-ink** [comment]
Hi Jonathan
I am having a hard time finding specific profile_user action documentation - but I am happy to manually trigger some other function that is hooked to the SF update (say, wp_update_user or something) without modifying it. Would wp_update_user be the best? Otherwise I'll go the AJAX route, but prefer it entirely server-side.
Thanks!

**Comment by jonathanstegall** [comment]
Sure. Sorry, `profile_update` is the correct WordPress hook I should've mentioned. You can read about it here: https://developer.wordpress.org/reference/hooks/profile_update/. It runs any time the user object is updated. I'm inclined to think `wp_update_user` would work best, as you say; it will definitely cause that hook to run.

**Comment by social-ink** [comment]
Great, I'll do that. Thanks Jonathan for your rapid assistance.
