### ISSUE TITLE
Changed SF sandbox, using same App. Now users aren't syncing. 

### ISSUE THREAD

**Issue by pixelparlordev** [MinnPost/object-sync-for-salesforce#172]
### Expected behavior
Syncing new user to and from salesforce
### Actual behavior
creates error and generating a tmp username in wordpress an not syncing to salesforce
### Steps to reproduce behavior

Hi. I have been developing with one sandbox with a specific app, and everything was working fine. I was able to sync user info back and forth. Then we switched to a new test sandbox, with the exact same app. Now, for some reason I can't create a new user and sync to salesforce.

When I try to click add to salesforce as a new user, I get a user name like tmp_sf_5aecbe07d3ca11.77821783

Then I try to push or pull and it has an error that says:

Provided external ID field does not exist or is not accessible: tmp_sf_5aecbe07d3ca11.77821783
And it says this for everything. For some reason If I were to disconnect and reconnect with the old sandbox I can update info. So I am just wondering if anyone knows what these errors are.

Mapping error example

Push to Salesforce | 12 | user | tmp_sf_5aecbe07d3ca11.77821783 | 2018-05-04 4:09:43pm

It seems like it says it's syncing to SF, but it really isn't. I am confused by this. This almost seems like something I should have caught, but it just isn't changing no matter wha I do.

**Comment by jonathanstegall** [comment]
Do you have logging enabled in the plugin? If so, are there any error logs before it gives you the external ID field message? The `tmp_` field is created when the plugin tries to sync, but fails. So there should be another error log before that happens.

**Comment by jonathanstegall** [comment]
While I'm thinking about this again, I'm curious if this has anything to do with the login state with the new sandbox (it may not).

To see if it does, you could try this:

1. Go to the Authorize tab in the plugin. Click Disconnect from Salesforce.
2. Go to the Settings tab and make sure all the credentials are correct for the new sandbox. I would expect that you might need a new consumer key/secret, but perhaps not. Either way, make sure.
3. Go back to the Authorize tab and click Connect to Salesforce.
4. If the plugin successfully connects to Salesforce, try your new user sync again and see if it has a different result.

**Comment by pixelparlordev** [comment]
Thanks for following up, I want to double check everything before pestering you haha. I have tried to disconnect and reconnect several times. I think it must be something with the specific application on the new sandbox (maybe the company we are partnering with has it locked or something?).

I basically duplicated our dev site, and it is still working well with out initial test site, but when I create the same app ont he new sandbox and link it to the second site, I now get this errors.

WP Side (while trying to push new user from salesforce, in user area of WP) :
invalid cross reference id



SF Side (while trying to pull users from salesforce, shows in authorize area of SF plugin even after re-auth) :
Salesforce successfully returned 6 Contact records. They are cached, and they were not loaded from the cache. This request did not require refreshing the Salesforce token.

**Comment by jonathanstegall** [comment]
The `invalid cross reference id` is the relevant part, I believe. This is a Salesforce API error message.

I'm not super experienced with it, but I believe it is often a permissions issue on the Salesforce side. That is, the Salesforce user that is authenticated with this plugin when you authorize doesn't have permissions that it needs.

https://success.salesforce.com/answers?id=90630000000gmJ5AAI is something I found. It has this part:

> It generally means that the objects you updated have ID fields in them that are filled with IDs that are either invalid or that your user does not have permissions to see.  It's also possible that the product ID field itself for these 4 failures is invalid or got corrupted prior to the update.
> 
> Anyway, for these 4 failed updates, check any IDs that are in them and see if you can get to them manually -- if you can't, then there's your smoking gun.

So I'm inclined to think you can do a few things:

1. In the App you've created in Salesforce, make sure it has all the permissions this plugin needs (at least "Perform requests on your behalf at any time" and "Access and manage your data (api).
2. I'm assuming you've already done that, so I think you'll probably need to investigate the Contact object (or whatever you're trying to sync with in Salesforce) and make sure that your Salesforce user can access everything. This could mean something to do with the Salesforce object type itself, all the way down to individual fields. Salesforce permissions get really granular at times, from what I've seen, and Salesforce seems to offer almost nothing to tell you what might be causing the problem, other than just manually checking everything.

**Comment by pixelparlordev** [comment]
Thanks for the feedback. I also think it has something to do with permissions, I duplicated the app and the settings. The only things that changed is the sandbox itself and the fields that they are syncing with. I checked, and I do have my fields named properly. So the only other problem could be that the permissions are maybe just not right quite yet. 

This seems evident by the fact that the users created on the SF side are showing int he authorize tabs, but aren't fully coming in to users. So this makes me think I have my auth settings accurate but the permission are just different on this sandbox.

**Comment by pixelparlordev** [comment]
I actually duplicated the site, made a new app, and it still works fine with the original sandbox. However the second site with the new sandbox and new app still isn't syncing. So it really has to be some sort of permissions issue.

Unless there is any way that there is cached information from the old authorization that would have interfered with re-authorizing to a new sandbox (I wouldn't think there is), it's probably doesn't have anything to do with the plugin.

Thanks for your help as always.

**Comment by pixelparlordev** [comment]
I recently spoke to the company that we are partnering with, that is handling the Salesforce. Through a conversation, I realized that the primary difference in the old and new (production) sandboxes is that while the account / record types in sandbox 1 are standard account types.
However, the settings in sandbox 2 have two unique features, those are. 

- Person Accounts
- Nonprofit Success Pack  (SPSP)

They mentioned this fundamentally changes the way accounts work in Salesforce. Our deep backup plan is to use standard account types, but ideally we'd like to use the above record / account types for this project. 

This is the only difference we could see. Also, I might have mentioned this before, but in addition to the field maps errors. the auth tab seems to be showing accounts that it is trying to pull in from Salesforce,  but won't actually make accounts for.

Would these unique account setups be making anything interfere with the syncing process?

I will include a few screen grabs from mapping errors and authorization tabs. Sorry if I am repeating myself in anyway.

These are some errors with some temp dummy accounts
<img width="1829" alt="screen shot 2018-05-09 at 11 44 08 am" src="https://user-images.githubusercontent.com/32943105/39824983-aeea0bea-537e-11e8-85a7-1f917dbf0117.png">

<img width="1828" alt="screen shot 2018-05-09 at 11 44 37 am" src="https://user-images.githubusercontent.com/32943105/39825041-d882ffc0-537e-11e8-93a9-69d8aa744e40.png">

**Comment by pixelparlordev** [comment]
You were right, it was a permissions setting. This is handled by another company so I was'nt able to make the changes, but we got it synced finally. Thanks again.
