### ISSUE TITLE
Unable to activate plugin on hosting providers test and production environments (pantheon.io)

### ISSUE THREAD

**Issue by BrianBenninger** [MinnPost/object-sync-for-salesforce#175]
This refers to a similar issue to https://wordpress.org/support/topic/activation-error-88/

However the fix that you put in place has not changed the behavior.

### Expected behavior
When I deploy the code to the Test environment I expect to be able to activate the object-sync-salesforce plugin.

### Actual behavior
Activating on the Dev environment works fine. After I've deployed my code to the test environment I receive this error.
Warning: include(/srv/bindings/d4048c549dc042399b39223fa054b74e/code/wp-content/plugins/object-sync-for-salesforce/vendor/composer/../pippinsplugins/wp-logging/WP_Logging.php): failed to open stream: No such file or directory in /srv/bindings/d4048c549dc042399b39223fa054b74e/code/wp-content/plugins/the-events-calendar/common/vendor/composer/ClassLoader.php on line 444 Warning: include(): Failed opening '/srv/bindings/d4048c549dc042399b39223fa054b74e/code/wp-content/plugins/object-sync-for-salesforce/vendor/composer/../pippinsplugins/wp-logging/WP_Logging.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /srv/bindings/d4048c549dc042399b39223fa054b74e/code/wp-content/plugins/the-events-calendar/common/vendor/composer/ClassLoader.php on line 444 Fatal error: Class 'WP_Logging' not found in /srv/bindings/d4048c549dc042399b39223fa054b74e/code/wp-content/plugins/object-sync-for-salesforce/classes/logging.php on line 15

### Steps to reproduce behavior
Get a pantheon site.
Download plugin on dev environment
deploy to test
try to activate plugin.

I have tried removing the gitignore files mentioned by @joepahl in activation-error-88 referenced above. But this has not solved my issue. Pantheon only lets you install plugins on Dev and then deploy up the deployment chain. I also can only sftp into dev and so I am unable to add the files that are not being deployed to test/production.

**Comment by jonathanstegall** [comment]
While I don't have access to a Pantheon site, I'm curious if they give you command line access. If so, are you able to run `composer install --no-dev --prefer-dist` on the plugin directory?

Certainly that is not a fix for the issue, but if you are able to do that it will let you use the plugin in the meantime. I am no composer expert, and it's difficult to fix something like this without being a Pantheon user.

**Comment by BrianBenninger** [comment]
They give you a version of a CLI called Terminus. I'm not incredibly familiar with all you can do with terminus but I will see if running composer install on the test environment is an option.

Not that you should. But, if you were inclined to look into this issue further, making a pantheon site is free. They only charge you when you go to launch and connect a DNS, etc.

If you're interested. https://pantheon.io/register

**Comment by jonathanstegall** [comment]
I tried creating a test site on Pantheon. I'm assuming this is not a normal workflow, but here's what I encountered:

1. Create the dev site
2. Install the plugin from the WordPress directory. It works fine.
3. Deploy the site from dev to test. At this point, the plugin is not there at all, and there's no Add New button. I see they've locked it down so folk only use the deploy button. I'm confused why it is not there at all rather than just missing the files you mentioned above, but maybe it's because I'm not using a git repository on the test?

Anyway, I'm not sure the best way to handle this. I imagine it might be possible to include all of the composer files in the plugin's git repo and maybe they would deploy correctly in that way? I'm reluctant to do that if there's any more standard way of handling this. I sent a message to Pantheon to ask if they have any recommendations for such things.

**Comment by jonathanstegall** [comment]
@BrianBenninger I think I've unwittingly fixed this issue. I noticed that a different change I made has shifted how test git repositories that contain this plugin work. If you could test it whenever you can, let me know. I'd like to know that this plugin works in a place like Pantheon, if possible.

**Comment by jonathanstegall** [comment]
Possible that this is fixed in commit cdf0654da670448ad4f62c872972b28809ebf905 but it does need some testing.

**Comment by jonathanstegall** [comment]
Tested in Pantheon with the #201 PR. Plugin can be deployed as it should, now.
