### ISSUE TITLE
Hey, how are you? Should not the "$result" variable be returned?

### ISSUE THREAD

**Issue by anarkaike** [MinnPost/object-sync-for-salesforce#180]
https://github.com/MinnPost/object-sync-for-salesforce/blob/51c1488dd95e617551f55f6e208ccc1a73fcdf9c/classes/salesforce_push.php#L1003

**Comment by jonathanstegall** [comment]
No. That result is never used. That method works in one of two ways: 1) it sends data to Salesforce and creates a success log, 2) it tries to send data to Salesforce fails, and creates an error log. It could return $result, but there wouldn't be any benefit to it doing so.

**Comment by anarkaike** [comment]
Thank you very much!
