### ISSUE TITLE
Issues Syncing Data of Pre-existing Objects In Salesforce

### ISSUE THREAD

**Issue by pixelparlordev** [MinnPost/object-sync-for-salesforce#182]
### Expected behavior

WP Members with subscriber-level user permissions sync to corresponding account objects in Salesforce. 

### Actual behavior

Member/User is not able to find it's matching object on the Salesforce side that was pre-existing. Plugin is offering to push data as new Salesforce object, which wasn't previously happening in test sandbox.

### Steps to reproduce behavior

We are trying to map pre-existing users in Memberpress, with accounts that are in the Salesforce Environment, but the plugin is saying :

This user is not mapped to an object in Salesforce. You can run a push to send this object to Salesforce, which will cause it to follow the plugin’s normal mapping conventions, or you can create a manual link to a Salesforce object.

How would you connect to it’s pre-existing counterpart within Salesforce, instead of writing the user in as a new object? I wasn't able to find enough info on "pre-match", but I see this a thing, and I am wondering if it relevant to our issue. I just wasn't able to find enough info on it.

A bit of background - We were testing all kinds scenarios throughout the past months and never really hit a roadblock in testing with basic account types on Salesforce sandbox. When we were doing this, we were simple signing up test users and able to sync both ways from that point on. This worked fine as long as the user was created in Wordpress, and still works that way.

However, in the Production environment we were connect to, it seems like it was a very loose system where memberships were signed up as "opportunities". The SF specialists that we partnered with for this project was able to clean up and separate the active accounts they then moved the accounts into our App so we couldn't sync to the accounts. 

To process the members correctly, we had to export them from Salesforce and import them into Memberpress as subscriber level users. So now we have all of the users, and their relevant date setup identical on both sides, but we can't seem to connect to those objects on the Salesforce side. 

Maybe this way of taking the whole user base from Saleforce, importing into Memberpress, then attempting to sync that with it's duplicate in Salesforce might have complicated things? Like I said it works the way that we have been using it, where new users get created and synced no problem.

So I guess my questions would be -

"How does Object Sync actually find pre-existing-matching objects in Salesforce; ie: is this pre-match?"

"Can I set up Object Sync to sync with both pre-existing objects and retain the way it currently works, where the newly signed up users get created over on the SF side as new objects?"

**Comment by jonathanstegall** [comment]
It seems to me like both of your recent GitHub issues are the same problem. If that is not correct, do let me know, but I'll assume they are the same and try to address on this one. Please close or clarify the other issue if you can.

The first thing to know is that this plugin does not officially support syncing pre-existing data. There's a little bit of talk about a solution in the interface for this in issue #98 on this repository, but thus far I haven't built the solution yet.

However there is functionality in this plugin to create object maps with a JSON import. If you can create a JSON with the data that should be mapped, you can import it and the plugin will use those object maps whenever data changes.

You can use the Import & Export tab for this. Here's an example export of object maps. You would need to change the data so that it has the correct values for each corresponding Salesforce and WordPress object.

```
{
   "object_maps":[
      {
         "id":"41",
         "wordpress_id":"8",
         "salesforce_id":"006W000000DtL5yIAF",
         "wordpress_object":"post",
         "created":"2018-03-12 03:00:24",
         "object_updated":"0000-00-00 00:00:00",
         "last_sync":"2018-03-09 17:29:41",
         "last_sync_action":"push",
         "last_sync_status":"1",
         "last_sync_message":"Mapping object updated via function: salesforce_push_sync_rest"
      },
      {
         "id":"50",
         "wordpress_id":"51",
         "salesforce_id":"00QW0000006ZcBPMA0",
         "wordpress_object":"app",
         "created":"2018-03-12 03:07:00",
         "object_updated":"0000-00-00 00:00:00",
         "last_sync":"2018-03-12 03:07:00",
         "last_sync_action":"pull",
         "last_sync_status":"1",
         "last_sync_message":"Mapping object created via function: create_object_map"
      },
      {
         "id":"53",
         "wordpress_id":"58",
         "salesforce_id":"00QW0000006ZcC3MAK",
         "wordpress_object":"app",
         "created":"2018-03-12 03:20:50",
         "object_updated":"0000-00-00 00:00:00",
         "last_sync":"2018-03-12 03:20:50",
         "last_sync_action":"push",
         "last_sync_status":"1",
         "last_sync_message":"Mapping object updated via function: salesforce_push_sync_rest"
      },
      {
         "id":"141",
         "wordpress_id":"621",
         "salesforce_id":"006W000000E5vy2IAB",
         "wordpress_object":"donation",
         "created":"2018-04-17 13:52:26",
         "object_updated":"0000-00-00 00:00:00",
         "last_sync":"2018-04-17 13:52:26",
         "last_sync_action":"pull",
         "last_sync_status":"1",
         "last_sync_message":"Mapping object created via function: create_object_map"
      },
      {
         "id":"142",
         "wordpress_id":"623",
         "salesforce_id":"006W000000E5vyWIAR",
         "wordpress_object":"donation",
         "created":"2018-04-17 13:56:46",
         "object_updated":"0000-00-00 00:00:00",
         "last_sync":"2018-04-17 13:56:46",
         "last_sync_action":"pull",
         "last_sync_status":"1",
         "last_sync_message":"Mapping object created via function: create_object_map"
      },
      {
         "id":"66",
         "wordpress_id":"23",
         "salesforce_id":"003W000000mt8zSIAQ",
         "wordpress_object":"user",
         "created":"2018-03-30 17:57:54",
         "object_updated":"2018-05-07 15:46:01",
         "last_sync":"2018-05-07 15:46:01",
         "last_sync_action":"pull",
         "last_sync_status":"1",
         "last_sync_message":"Mapping object updated via function: salesforce_pull_process_records"
      },
      {
         "id":"45",
         "wordpress_id":"7",
         "salesforce_id":"003W000000loGBaIAM",
         "wordpress_object":"user",
         "created":"2018-03-12 03:00:24",
         "object_updated":"2018-05-07 17:32:16",
         "last_sync":"2018-05-07 17:32:17",
         "last_sync_action":"pull",
         "last_sync_status":"1",
         "last_sync_message":"Mapping object updated via function: salesforce_pull_process_records"
      },
      {
         "id":"75",
         "wordpress_id":"32",
         "salesforce_id":"003W000000o9XWtIAM",
         "wordpress_object":"user",
         "created":"2018-03-31 05:10:21",
         "object_updated":"2018-05-07 17:32:18",
         "last_sync":"2018-05-07 17:32:19",
         "last_sync_action":"pull",
         "last_sync_status":"1",
         "last_sync_message":"Mapping object updated via function: salesforce_pull_process_records"
      },
      {
         "id":"62",
         "wordpress_id":"19",
         "salesforce_id":"003W000000jr4gKIAQ",
         "wordpress_object":"user",
         "created":"2018-03-27 17:22:59",
         "object_updated":"2018-06-06 13:01:32",
         "last_sync":"2018-06-06 13:01:45",
         "last_sync_action":"push",
         "last_sync_status":"1",
         "last_sync_message":"Mapping object updated via function: salesforce_push_sync_rest"
      }
   ]
}
```

You can also just do this manually in the MySQL table `wp_object_sync_sf_object_map`. Either should work.

To your other question, the prematch field basically works like this: if there is already data in Salesforce or in WordPress, and you add new data, the plugin will attempt to use prematch fields to see if the records are the same, and if they are it will connect them rather than creating new records.

For example, if you have a Contact in Salesforce with a certain email address, and a user registers for an account in WordPress, if the email field is a prematch, the plugin would map the new user to the existing Contact rather than creating a new one.

Prematch does not relate to pre-existing data aside from that; as I say, this plugin does not officially support mapping pre-existing data (other than with import and export) yet, although I hope it will at some point.

**Comment by pixelparlordev** [comment]
Thanks for this, my only question is that we all of the users on Memberpress already, and their memberships have been processed. So would this mess with anything in the membership settings? They have their own importer, so wasn’t sure if this would create a conflict.

**Comment by jonathanstegall** [comment]
In this plugin's case, the only thing the import feature does is create rows in this plugin's tables. So if you were to create an import with only object maps, all it would do is create rows in the `wp_object_sync_sf_object_map` table.

It does not affect WordPress users at all, but it does tell the plugin to track updates to matched items moving forward.

**Comment by pixelparlordev** [comment]
So for example I can just make a file called members.json, and save this specific code in just like this (attached example), then import through the Wordpress importer through tools > import ?





But obviously one block for each user, then import that into. Would this file need to have anything else to it?

**Comment by jonathanstegall** [comment]
JSON attachments don't come through GitHub, but if you follow my JSON code example above, I think you should be fine. You might want to run it through a JSON linter if you have the skills for that, but that is up to you.

The important parts for each individual item in the JSON are:
- `wordpress_id` - this is the ID of the item that should be mapped from WordPress. So it might be a user, a post, a custom object type, whatever.
- `salesforce_id` - this is the Salesforce ID value. It is case sensitive.
- `wordpress_object` - this is the WordPress object type's name. Not the label that allows spacing, but the name. So user, post, etc.

The other fields don't matter as much. The `id` and `created` values will be created by the plugin itself when it saves the rows in the database.

The standard "please back up your database first, if it is a production database" warning definitely applies here.

**Comment by jonathanstegall** [comment]
Also, please do either close, if it is the same as this one, or update, if it is different, the other issue you submitted here.

**Comment by pixelparlordev** [comment]
Ok cool thanks, I guess i wil close it? It kind fo seems like you mly have teo choices with this plugin currently, let me know itf this is accurate.

Yoiu can either -

- Sync new objects to SF

- Use this Json file to sync to connect the two pre existing objects, then it will sync fine after that initial mapping.

Thanks

Rob Williams
Senior Developer | Pixel Parlor
phone: (646) 713-4772
site: www.pixelparlor.com
email: rob_williams@pixelparlor.com
address: 2424 E York St #235, Philadelphia, PA 19125

**Comment by pixelparlordev** [comment]
The onlky thing I am a little confused about is why there seems to be two wordpress id’s ? But yeah I will def close the issue, as it seems this is the onky option for this method.

  {
"id":"66",
"wordpress_id":"23",
"salesforce_id":"003W000000mt8zSIAQ",
"wordpress_object":"user",
"created":"2018-03-30 17:57:54",
"object_updated":"2018-05-07 15:46:01",
"last_sync":"2018-05-07 15:46:01",
"last_sync_action":"pull",
"last_sync_status":"1",
"last_sync_message":"Mapping object updated via function: salesforce_pull_process_records"
}

Rob Williams
Senior Developer | Pixel Parlor
phone: (646) 713-4772
site: www.pixelparlor.com
email: rob_williams@pixelparlor.com
address: 2424 E York St #235, Philadelphia, PA 19125

**Comment by jonathanstegall** [comment]
Sure, let me specify those IDs.

1. `id` is for the object map table itself. So each row (each object map) in that table has an ID. It's just an autoincrement field, so it is only used by this plugin to access object maps. It is an important field, but not beyond this plugin
2. `wordpress_id` is the WordPress object that is *being* mapped. So if you had a user, the `wp_user` table has an ID column with a unique ID for each user in the users table. That is what goes into this field.

**Comment by pixelparlordev** [comment]
Ok cool thanks again. I think I am clear on this now. One last thing about the ID...
If the objects already exist on both sides, am I supposed to be finding the ID somewhere? Meaning I know where to find the WP ID and the SF ID. Just wondering that is already coming from somewhere or I just number it sequentially like "1, 2, 3" and so on for each user block in the json file.

**Comment by pixelparlordev** [comment]
Ok great, thanks again! So since already have the wp id and sf id can I just leave everything else blank and only have a file with this info?

{
   "wordpress_id":"23",
   "salesforce_id":"003W000000mt8zSIAQ",
   "wordpress_object":"user",
},
{
   "wordpress_id":"24",
   "salesforce_id":"003W000001mt8zSIAZ",
   "wordpress_object":"user",
}

...and so on, or does it need to show some sort of value to actually work? Like this -

{
   "id":"1",
   "wordpress_id":"23",
   "salesforce_id":"003W000001mt8zSIAZ",
   "wordpress_object":"user",
}

this is my final question, sorry for all of this but I just wanted to be double sure since this wasn't even and issue last week and now I have to do this on a live site, so I just want to be sure I do it right the first time.

**Comment by jonathanstegall** [comment]
I would go ahead and put an "id" in there. As I say the plugin will generate one for you, but it lets you keep track better I think.

**Comment by jonathanstegall** [comment]
And do back up the database, since it's a live site.

**Comment by pixelparlordev** [comment]
Ok great, and all other fields seems to be optional after wp object field

All this - 
   "created":"2018-03-30 17:57:54",
   "object_updated":"2018-05-07 15:46:01",
   "last_sync":"2018-05-07 15:46:01",
   "last_sync_action":"pull",
   "last_sync_status":"1",
   "last_sync_message":"Mapping object updated via function: salesforce_pull_process_records"

Yeah I will def back up the database.

**Comment by jonathanstegall** [comment]
Yes. When the plugin creates new rows, it will do the created field for you, and the other fields will be filled in whenever the plugin acts on the matching data.

**Comment by pixelparlordev** [comment]
Awesome thanks for all the additional info as always! I will close this now.

**Comment by jonathanstegall** [comment]
Also I do realize I need to create some documentation for the import/export feature. This is helpful to let me know what to include, when I can get to it.

**Comment by pixelparlordev** [comment]
Awesome great to here it. 

This was a huge project and it's just really a shame that we had the perfect working model all throughout Dev, then we were told we couldn't map to new SF objects, and merge the data with the old accounts to retain campaigns and history for whatever reason. We just randomly found this out a day before we launched the site This basically put a bunch of holes in our careful plans, and I am kind of at a loss as to what we can even do at this point. So it's really great that there was a work around for this.

**Comment by pixelparlordev** [comment]
Sorry One last stupid question. I am trying to import this json file into worpdress and it is saying. 

Sorry, there has been an error.
This does not appear to be a WXR file, missing/invalid WXR version number

Am I importing into wrong area?
