### ISSUE TITLE
TMP_SF User Error every time all of the sudden.

### ISSUE THREAD

**Issue by pixelparlordev** [MinnPost/object-sync-for-salesforce#184]

**Comment by pixelparlordev** [comment]
For some reason the plugin will only create messages like this for every user, and I am fairly certain I am using the same setting as before. I am trying very hard to not ask stupid questions here, but I am completely stuck on this. Which is a shame, because I took pretty tight notes on past conversations, and for some reason that isn't working.
 
I have seen this message here and there before, but it was always because of something very simple that was off, and I was always able to finish it and move on. But now I am seeing it with almost nothing configured except what I need. I tried with a very simple setup, where I sign up a new user and sync the same exact field that I had success with before.

I am going to attach my error logs and a screenshot in case it looks like anything is off. But I did based this on what I had set up prior to not getting anything to work. 

Same errors no matter how many time I clear cache, and errors. Am I missing something simple or is this a greater problem? I would just like make a test run to see the simplest new account show up in salesforce at this point. 

**Error Examples**

Provided external ID field does not exist or is not accessible: tmp_sf_5b1a055adb0e05.96896484

Push to Salesforce | 31 | user | tmp_sf_5b1a0c4d19fc16.76120763 | 2018-06-08 12:55:41am

Salesforce Id | tmp_sf_5b1a15d7760042.95863246 |
-- | -- | --
Provided external ID field does not exist or is not accessible: tmp_sf_5b1a15d7760042.95863246 |  
push |  
error |  
2018-06-08 01:36:24 |  
Push to Salesforce Pull from Salesforce


**All Of My Settings**

https://i.imgur.com/09zQ9D7.jpg

https://imgur.com/OY1VCzu

https://imgur.com/DEyNYMC

https://imgur.com/wTBWftE

https://imgur.com/j2itZgF

https://imgur.com/KENKwHE

I am just trying to create a new account in Salesforce (for now), by writing the user name to salesforce account ID. I have tried to check my work against all the docs I could find on this and I haven't been able to troubleshoot it. Once I get over this new issue I can apply all the past settings hopefully complete this.

**Comment by pixelparlordev** [comment]
I noticed that I get this

https://i.imgur.com/ltsi6oK.jpg

Then I get this...

https://i.imgur.com/ImNdggQ.jpg

Does any of this point to Salesforce being the cause? I don't think I am doing anything different at all. I have checked so many times for one missing box that I might have missed, but I don't see anything that is off. It seems slightly different than the previous issue where you had me re-auth.

https://github.com/MinnPost/object-sync-for-salesforce/issues/172

I have been trying to reference this to avoid asking the same thing twice, but this is trickier than normal.

**Comment by jonathanstegall** [comment]
If the only message in the log is this:

```
Provided external ID field does not exist or is not accessible: tmp_sf_5b1a055adb0e05.96896484
```

You should try deleting the mapping error row (from the Mapping Errors tab) and then try that item again. That temp ID is just that - a temp ID - so it will never exist in Salesforce. It should always be deleted or replaced, or it'll keep erroring.

I'm not sure if that is the only issue though; some error maybe had to originally keep it from pushing.

**Comment by pixelparlordev** [comment]
Yeah I have been doing all of that. And It just keeps doing the same thing.

**Comment by jonathanstegall** [comment]
So let me see if I understand you correctly:

1. You can start with no relevant object maps. That is, there are zero rows in the Mapping Errors tab, and zero errors in the Logs menu.
2. You can create a new user in WordPress that matches a fieldmap, and it fails to be pushed to Salesforce.
3. The plugin creates a Log post that says the temp ID does not exist in Salesforce, and a corresponding row in the Mapping Errors tab. There are no other error logs.

If this is the case, it would seem to be a Salesforce configuration issue of some kind. This plugin will create error logs - not in the Mapping Errors tab but in the Logs - if Salesforce returns error messages. If it is just creating temp ids over and over, this means something in Salesforce is preventing it from ever saving data there, but also preventing Salesforce from returning relevant error messages.

For an example when Salesforce is configured correctly but errors are happening:

1. You could start with no relevant object maps, no errors, etc.
2. You could create a new WP user. It might fail for some normal data issue, like a missing required field.
3. The plugin would create a Log post with that specific error message (for example, our Contact object requires a LastName value, so it would log that as a missing field).

**Comment by pixelparlordev** [comment]
It won't even let me sync unless I pick one map though. Unless I am misunderstanding you.

**Comment by jonathanstegall** [comment]
An object map is not the same as a fieldmap. A fieldmap is when you say the user object maps to the contact object, for example. An object map is the row that connects a single user to a single contact.

When the plugin tries to push data to Salesforce, it creates an object map row with a temporary ID while it waits for the API response from Salesforce. That's why you see the temp ID. But those temp IDs can cause issues if they linger, hence the edit/delete options in that tab.

**Comment by pixelparlordev** [comment]
So you are saying something, be it a setting or a config error is not allowing SF to ping back to the site? So to speak? That would be great if that were the case becasue then I would have some source for my troubleshooting marathon.

**Comment by jonathanstegall** [comment]
I certainly can't speak to your Salesforce config, but if there is a standard API error message (something like a missing field, for example) there should be a Log post in the Logs menu I mentioned earlier.

Here's an example of an error log it would create in normal operation:

![image](https://user-images.githubusercontent.com/435342/41166446-dc5205b2-6b05-11e8-91b7-ac053785638c.png)

If it is never creating an error log like that, I think it's because of some Salesforce issue.

**Comment by pixelparlordev** [comment]
I see. Yeah I just get tmp_sf and can’t find this external ID every time regardless of what I try. What’s scary is I can’t make anything connect on the most remedial level, everything I have built top to this point seemingly stopped out of the blue. I have rechecked my auth setting so many time I lost count. But I guess that has to be the source?

**Comment by jonathanstegall** [comment]
The external ID you mention will never exist in Salesforce because it's an ID that the plugin randomly generates while it waits for a response from Salesforce. It is unable to work its normal update process, for whatever reason.

You should maybe try disconnecting the plugin and reconnecting it.

![image](https://user-images.githubusercontent.com/435342/41167079-82eaa4aa-6b07-11e8-82ef-6175235fd46b.png)

If you can disconnect the plugin from Salesforce and then can still reconnect, it probably is not authentication related but rather related to the object itself, or some of its fields, in Salesforce. Those things all have their own permissions that are not authentication related.

**Comment by pixelparlordev** [comment]
Ha ha, this is also something I have done so many times. I tried to make a personal guide for myself on usage and troubleshooting, becasue I feel bad asking abut seemingly the same issue.

It seems that no matter if I delete the plugin and clear there data, and delete the app and create a new one and re-authorize, I still get that error. I have done this over and and over, clearing everything in my path, and I can’t even get one clean push at the most incredibly basic level. 

I am going to just keep removing everything and starting from scratch I guess.

**Comment by pixelparlordev** [comment]
It got to the point where I had to build my own test SF sandboxes and recreate the account settings. I had to start with just a blank site and a blank sandbox. Then I worked it the whole way up to our dev site syncing with my test sandbox, which revealed that something had changed within the 3-4 sandboxes we were working with that was the reason for not being able to create users, or sync. 

The problem is still unresolved, but it's not an object sync issue, so now we can at least narrow down the real problem. Furthermore I know a lot about syncing objects from WP to SF. So this was great experience.

Thanks again for all the help again Jonathan. You really know your stuff.

**Comment by jonathanstegall** [comment]
Migrating from one sandbox to another is, in my limited experience, kind of a beast of a task. Permissions, especially, get lost regularly and then all kinds of weird things happen. I don't know if that's what you're encountering, but I have certainly had it happen.

**Comment by rwdevpixelparlor** [comment]
I am looking int he error logs you had me turn on the other day and I keep seeing this pop up every other minute. Would this have anything to do with the fact that we still can't get any nw users to sync, but only on the final production environment. 

Debug: on Salesforce API HTTP Request to URL: https://na87.salesforce.com/services/data.
