### ISSUE TITLE
Better dropdowns for WordPress and Salesforce fields

### ISSUE THREAD

**Issue by jonathanstegall** [MinnPost/object-sync-for-salesforce#185]
### Expected behavior

I think it would be nice to have a search + select field for both these dropdowns.

Maybe like this image from CMB2.

https://raw.githubusercontent.com/mustardBees/cmb-field-select2/master/screenshot-1.png

### Actual behavior

It is just a (potentially really big) dropdown

### Steps to reproduce behavior

Add/edit a fieldmap

### Branch for this work

[185-177-improve-fieldmap-dropdowns branch](/MinnPost/object-sync-for-salesforce/tree/185-177-improve-fieldmap-dropdowns)

**Comment by jonathanstegall** [comment]
I don't know, I think it might entail making a select2 theme for this that better matches the WP admin styles. For example here's the Sass for the default select2 theme. https://github.com/select2/select2/tree/develop/src/scss/theme/default

**Comment by pixelparlordev** [comment]
Meant I started going about doing that, haven’t figured anything out yet haha. Don’t want to take credit for things I can’t figure out yet :)

**Comment by jonathanstegall** [comment]
It doesn't look very difficult to make a select2 theme, with some CSS/Sass. Object Sync for Salesforce is already using Sass, so it would probably fit in nicely.

For example in the select2 repo, the default theme only has three Sass files. https://github.com/select2/select2/tree/develop/src/scss/theme/default

**Comment by jonathanstegall** [comment]
Here's the branch of this plugin. It does have select2 operating, but no theming has been done and it probably needs some testing to make sure it doesn't miss setting up the select2 in certain spots, and/or to make sure no data is getting lost. https://github.com/MinnPost/object-sync-for-salesforce/tree/185-177-improve-fieldmap-dropdowns
