### ISSUE TITLE
Blank/empty date or datetime fields are not handled correctly when pulling from SF

### ISSUE THREAD

**Issue by synthetiv** [MinnPost/object-sync-for-salesforce#186]
Hi there! First, thank you for this plugin, which has saved me tons of work and many headaches.

Unfortunately, I've just recently run into some surprising behavior around date fields, which I'm sure applies to datetime fields as well: 

### Expected behavior

When syncing Salesforce contacts and WordPress users (or probably any other object types, but these are the ones I've tested), if there's a non-required date field in SF that's mapped to a meta field in WP, and that field is left blank in a Salesforce record that then gets pulled to WordPress, the corresponding WordPress field will be set to today's date.

### Actual behavior

The WP meta field should be set to an empty string – or the meta value could be deleted, but an empty string is probably better for most applications.

### Steps to reproduce behavior

1. Create a date field in Salesforce
2. Create a field map that maps the date field to a WordPress field
3. Create a record in Salesforce and leave the date field blank
4. Trigger a pull from Salesforce to WordPress
5. Check the value of the WP field

I believe the problem is with this code block: https://github.com/MinnPost/object-sync-for-salesforce/blob/master/classes/salesforce_mapping.php#L785 – the data type conversion code doesn't allow for null or empty values coming from Salesforce.

I'd be happy to submit a PR for this, but first I'd appreciate a confirmation that this is really an issue and that there isn't some other way of getting around this behavior that I'm missing.

Thanks again!

**Comment by synthetiv** [comment]
Alright, so I dug into this quite a bit more than necessary before realizing that there was a very, very simple way to fix this issue – which I'm submitting a PR for.

But, in the course of my digging, I noticed something sorta-related that confused me a lot at first, which I thought I'd ask about.

Because WordPress's `update_{object_type}_meta()` functions return FALSE when the meta value provided matches an existing meta value in the database, this plugin's `Object_Sync_Sf_WordPress::{object_type}_update()` functions very frequently return values that would appear to represent failures – see [this code block](https://github.com/MinnPost/object-sync-for-salesforce/blob/6426e58/classes/wordpress.php#L1056). For instance, if `user_update()` is called to update a user and most of the field values coming from Salesforce haven't changed since the last pull, then `update_user_meta()` will return false for most fields, so (in that block) `$success` will be set to false, and `$errors` will be populated with a bunch of fields that haven't really _failed_ to update, but just didn't _need_ an update.

This totally baffled me at first (how did syncing work at all if something so common could be considered an "error?"), until I realized that the `*_update()` functions' return values are never really used anywhere! Based other comments in classes/salesforce_pull.php, I'm guessing that this error-catching code is actually just a holdover from the Drupal module – is that right?

**Comment by jonathanstegall** [comment]
Thanks for checking on this. I haven't seen any cases where errors are caused, but it does indeed use `update_post_meta`, etc. It is not a holdover from the Drupal module. I'd curious if you've encountered errors from this, but otherwise as far as I know, it does work.

**Comment by synthetiv** [comment]
Yeah, I haven't seen any errors _logged_ with this because the return values of `user_update()`, etc. are ignored. It was really just something that confused me while I was looking through the code.
