### ISSUE TITLE
Can't find media object to either pull or push images.

### ISSUE THREAD

**Issue by geopap44** [MinnPost/object-sync-for-salesforce#190]
Hi,
We have a RealEstate property management website, and our Salesforce site has properties where we attach images to each of them...  Can I get it to sync to Wordpress those images (media library / Uploads folder)?  The property ID is the unique identifier for each listing/property.  
When I successfully configured object sync and I tried to look for the field mappings that reference those images, I couldn't find it.   Please advise.

**Comment by jonathanstegall** [comment]
This plugin can sync attachments from the media library, but if you don't see the field mappings, it may be that they're not using standard methods from WordPress.

This plugin has abundant developer hooks that you may be able to use, but this can be rather complicated.

**Comment by geopap44** [comment]
Ok, thanks.  I will try to dig in more to see if I can locate them in some of the other SF objects.  If I can't see them, then I will get in touch with our SF developer (Visualforce) and ask him to create the appropriate WP methods for the custom fields he created.

**Comment by geopap44** [comment]
Is this correct?  I found the Attachment object in WP and SF (see screenshot attachment).
[
![salesforce_image_attachment](https://user-images.githubusercontent.com/41152396/42743979-07d8f244-88f3-11e8-95a9-62490fe9ffdd.png)
](url)

**Comment by jonathanstegall** [comment]
@geopap44 I didn't see your comment here. The attachment object in WordPress is, indeed, any item inside the WordPress media library. It can be a little tricky because it is dealing with both files and with database rows, but Object Sync for Salesforce provides as much support for this as it can, by default, and the hooks can do more as well.

As for the Salesforce attachment object, you'd want to ask your Salesforce developer about that. It may be that he has other ways of storing the attachment data in Salesforce.

We don't provide support for using the hooks, to be clear.

**Comment by geopap44** [comment]
Hi Jonathan,
I greatly appreciate your added input on this matter.  The developer I mentioned to you in my previous email isn’t a SF developer; he’s our website developer..  He may be contacting you via GitHub on other issues (besides this one) that he may experience by using your plugin.
Keep up the great work.  So far, this project has my full support…

George Papas
IT Director, Thailand

[cid:image021.jpg@01D321A3.BA82DA80]<http://www.wwf.sg/business/asian_tigers_mobility_group.cfm>

Dir: +662 687 7918   |   Tel: +662 687 7888   |   Fax: +662 687 7999   |   Mobile: +666 3208 5460   |
george@asiantigers-thailand.com<mailto:george@asiantigers-thailand.com>   |   www.asiantigers-mobility.com<http://www.asiantigers-mobility.com/>   |   Follow us on: [cid:image009.png@01D321A3.BA82DA80] <https://www.facebook.com/asiantigersgroup>    [cid:image020.jpg@01D321A3.BA82DA80] <http://www.linkedin.com/company/asiantigersmobility>

Policy Declarations: Data Privacy<https://www.asiantigers-mobility.com/wp-content/uploads/2018/05/Privacy-Policy.pdf>   |   Anti-Bribery<https://www.asiantigers-mobility.com/wp-content/uploads/2017/08/Anti-Bribery_Anti-Corruption.pdf>   |   Environment<https://www.asiantigers-mobility.com/wp-content/uploads/2017/09/Evironmental-Policy.pdf>

This e-mail may contain confidential and/or privileged information. If you are not the intended recipient or received this e-mail in error, please notify the sender immediately and destroy this e-mail. Any unauthorized copying, editing, disclosure or distribution of the material in this e-mail is strictly forbidden and may be unlawful.
