### ISSUE TITLE
Issue with lightning version?

### ISSUE THREAD

**Issue by michaelcabus** [MinnPost/object-sync-for-salesforce#194]
Everything is mapped, however I am getting this error message in the log

Error: 400: on Salesforce http request
<p>URL: https://na73.salesforce.com/services/data/v42.0/sobjects/Contact</p><p>Message: No such column &#039;RecordTypeId&#039; on sobject of type Contact</p><p>Code: 400

I am using the WP give donation plugin.

I am noticing my URL for Salesforce is:

https://na73.lightning.force.com

Is there some code modification needed, perhaps the URL is not being found?

**Comment by jonathanstegall** [comment]
I haven't tried this plugin with Lightning yet, but I doubt the URL is the issue. Certainly you would be getting a different error message if it was not able to find the URL.

It looks like it's trying to find a column called RecordTypeId on the Contact object. At least by default, the Contact object does not have that column, as far as I know. But I'm not sure why the plugin would be looking for that column on that object.

When this happens are you pushing data to Salesforce or pulling it from Salesforce?

**Comment by jonathanstegall** [comment]
This is definitely not a lightning issue. As such, I'm going to close it, pending any further information.
