### ISSUE TITLE
How attachment sync work from SalesForce to WordPress?

### ISSUE THREAD

**Issue by Suresh-Lakum** [MinnPost/object-sync-for-salesforce#199]
### Help Needed
Hello,

I am very new with this plugin. I have configured it correctly. All data is syncing from SF to WP. 
But I have notice that attachments are not. Do I need to configure it separately? Can you guide me achieve this? Also I want to save attachment into Property Gallery.

Kind Regards,
Suresh

**Comment by jonathanstegall** [comment]
This plugin does have some basic support for attachments, but WordPress handles attachments in a lot of ways, especially if you are using a third party plugin. Most likely, you will need to use our developer hooks to achieve this. Especially if Property Gallery is a third party plugin.

We don't really provide any support for the third party hooks, but you can read some documentation about them here: https://github.com/MinnPost/object-sync-for-salesforce/blob/master/docs/all-developer-hooks.md
