### ISSUE TITLE
Large changesets don't finish with ActionScheduler

### ISSUE THREAD

**Issue by jonathanstegall** [MinnPost/object-sync-for-salesforce#204]
### Expected behavior

ActionScheduler should be able to process API requests, no matter how large the changesets are, based on the batch settings.

### Actual behavior

The library is complicated and I don't entirely understand how it processes its queue, but I believe it stops running calls at some threshold.

### Steps to reproduce behavior

See [this issue](https://wordpress.org/support/topic/what-happens-when-update-a-very-large-number-of-records-in-salesforce-at-once/).

**Comment by jonathanstegall** [comment]
We need to determine whether this is only an issue with pull requests (which is where we've seen it) or if it is also a problem on push requests.

**Comment by jonathanstegall** [comment]
I've made a [branch](https://github.com/MinnPost/object-sync-for-salesforce/tree/204-handle-large-changesets) to deal with this issue.

**Comment by charmoney** [comment]
Hi @jonathanstegall -- we've got an end user of the plugin who is running into this issue during pulls of 2,000 - 4,000 records every few weeks.

The sites we're running the plugin on all either use immediate push or only generate small change sets (no more than 1-2 dozen).  I can't chime in whether or not the issue is present on large push requests batches.

They're curious if, as a workaround, they can revert back to version 1.3.9 before the transition to Action Scheduler. I suspected not, because of the significant DB changes the plugin performed as part of the 1.3.9 to 1.4.0 update. Do you know if that's correct? Or is rolling back for now a viable option?

**Comment by jonathanstegall** [comment]
@charmoney I haven't tested rolling back, but I think it would still work. They would definitely have to resave fieldmaps and schedule settings, though. I believe the queue would go back to the way it was once those things were resaved.

I'm working on a fix for this currently, in any case. I hope to determine what's happening shortly.

**Comment by charmoney** [comment]
Thanks @jonathanstegall -- I'll let them know it's a possibility.

I'll also check to see if they are interested in testing your PR in a non-production environment.

From skimming the diff, it looks like the core issue is SF returning far too many records during the initial SOQL select?

**Comment by jonathanstegall** [comment]
I believe the PR is not the correct fix, so far

**Comment by jonathanstegall** [comment]
What the issue is:

1. The plugin runs a query to get updated records (however many it finds) and batches them up.
2. It then saves a settings value for when it last ran this query. It does this because otherwise it gets into an infinite loop between push and pull.
3. It runs the query again, but it finds that no records have been updated **since** the last time it ran, thus it doesn't have any more records to process.

**Comment by jonathanstegall** [comment]
Okay, here is the issue:

1. The plugin makes an API call to Salesforce to get updated records, and stores the time when it makes the call.
2. Each API call gets records that have been updated since the last get updated records query.
3. The limit added in 1.4 (I think) limits the number of records returned by the API.

This is why it fails on any large result sets - it has already run the query, and so it doesn't see those records as having been updated.

I'm noticing that the Salesforce REST API documents the following header: `Sforce-Call-Options` which should itself accept a value of `batchSize`. After the batch size is reached, the API will paginate its results using the `nextRecordsUrl` parameter, which we already support.

The maybe unfortunate thing is that `batchSize` can only accept values between 200 and 2000.

I'm still testing to see if it actually works at all - the documentation is not helpful for PHP - but if it does, I think we need to make sure that this doesn't cause server crashes like the previous queue system did. But if it does not, we should be okay to implement this instead.

**Comment by jonathanstegall** [comment]
@charmoney I've updated this PR to what I think will be the correct fix. It undoes some of the changes from 1.4.0, but still uses ActionScheduler, which I hope will prevent any server performance/reliability issues.

I need to test this with some larger queries myself, but I think ultimately this will be the solution.

If it is, I plan to release it as the 1.5.0 milestone/version.

**Comment by jonathanstegall** [comment]
If this is successful, we can also close #29.

**Comment by jonathanstegall** [comment]
In my testing locally, this PR causes normal WordPress requests on the server to timeout (I tried one with 8,523 records). Salesforce, at least for me, is not respecting the `batchSize` setting when it's added to the `Sforce-Query-Options` header.

The docs suggest that Salesforce can just ignore this:
> The default is 2,000; the minimum is 200, and the maximum is 2,000. There is no guarantee that the requested batch size is the actual batch size. Changes are made as necessary to maximize performance.

Presumably this is not about the client's performance, but about Salesforce. My testing still returns 2000 records on the first call, even though my batchSize is set to 200.

The response does appear to continue on to the `nextRecordsUrl` parameter, and then it appears to keep on adding records to the queue, but clearly this is not viable.

**Comment by jonathanstegall** [comment]
Other possibilities for solving this:

1. When a query runs to get updated records, we could save a series of option values:
- timestamp the query is running (we already save this)
- count of last record processed in the query
- id of query itself?
2. Then when we run the query, we could indeed use a `limit` on what the API returns, and we could use an `offset` of the last record previously processed. The hard part is retrieving the correct timestamp for when the query actually started (possible reason for saving an iD?)

I don't like this idea; it feels like overkill for what we actually need, but it's worth putting it down to think about it.

**Comment by jonathanstegall** [comment]
I think the above is going to be necessary, and am currently working on an attempt to see if it works as it should. Here's the flow, as I'm seeing it:

1. Run an initial pull query with a configurable `limit` value. It will get updated records since the value of `pull_last_sync_type`. It will save a serialized value of the SOQL query as the `currently_pulling_query_type` option.
2. When the cron job runs again, it will run with the same last run time value, `pull_last_sync_type`, but it will add an `offset` value equal to the `limit` value. Thus it should get the next batch of records. Each time it runs, it will update the `currently_pulling_query_type` value with the serialized SOQL query (thus preserving the `offset` value so it can be incremented the next time).
3. The cron jobs will continue doing this until there are 0 records remaining. At that time, it will delete the `currently_pulling_query_type` option and update the `pull_last_sync_type` value to the current timestamp.

**Comment by jonathanstegall** [comment]
As of commit d5577abeb9186bdeec42566fcfbb3cfc6badae98, the above comment is in place on this PR. It needs a good bit of testing, but hopefully this will finally be the scalable solution.

**Comment by charmoney** [comment]
That approach makes sense @jonathanstegall.

I know with the WP background processing library, the related issue was that the `pull_last_sync_*` value would not be updated if the process crashed (due to memory or time limits), causing a situation where the same records would continually be re-processed and crash in the exact same way until the options table got too large and crashed the server.

When is the `currently_pulling_query_type` value updated with the new offset value exactly?  Before the last query runs? After the whole record set is processed? Or after each individual record is processed? (Assuming the SOQL offset is by record number, not page number.)

**Comment by jonathanstegall** [comment]
@charmoney it updates the `currently_pulling_query_` value at the end of each batch of updates. So if the limit was 25, it would run 25 records and then it would update that value.

When the recordset gets to zero remaining records, it then checks to see if there is an existing `currently_pulling_query_*` value, and if there is, it deletes it and updates the `pull_last_sync_*` value. So it's basically doing it by page number rather than by record number.

I haven't seen a process crash in this case, but here's how I expect that would go:

1. Plugin runs a query for modified records, and it returns 25 records (or whatever the limit is).
2. Let's say it makes it through 13 of them, adding them to the ActionScheduler queue.
3. The 14th one fails to be added to the queue and so it never updates the `currently_pulling_query_*` value.
4. The query runs again and it gets the same 25 records because the offset value in the query hasn't changed.

I guess the hypothetical benefit is that it wouldn't skip records that had failed instead of processing.  ActionScheduler wouldn't fill up the options table, but maybe this would still be problematic.

**Comment by jonathanstegall** [comment]
@charmoney Perhaps the solution is like this:

```
foreach ( $response['records'] as $key => $result ) {

	// set up the data and check its pull allowed stuff

	if ( false === $pull_allowed ) {
		update_option( $this->option_prefix . 'pull_last_sync_' . $type, current_time( 'timestamp', true ) );
		continue;
	}

	// add it to the queue

	// update the offset with the current key here instead
	// the key is zero based, but that is fine for a SOQL offset value

	// serialize the currently running soql query and store it for this type
	$serialized_query = maybe_serialize( $soql );
	update_option( $this->option_prefix . 'currently_pulling_query_' . $type, $serialized_query );

}
```

This would update the offset each time a record gets processed, so if the query had to be started over, it would know how far it had made it already.

**Comment by charmoney** [comment]
I like that algorithm.  A similar approach worked well for the old
scheduling system.  It is a bit more overhead on the option framework for
sure. But WP has that whole feature pretty well optimized.

In your hypothetical case, let's say the 14th record hits a clause in a
site's filter due with a fatal logic error.  The next time the sync ran, it
would re-process the record that failed. Over and over again until someone
noticed, which I think is reasonable.

However, the sync would not re-process records 1-13.  I know the sync
plugin itself doesn't do anything on the sync. But I could see possible use
cases leveraging the filters & actions to perform additional tasks that
would be a problem to repeat.

**Comment by jonathanstegall** [comment]
@charmoney yeah, I think this sounds reasonable, especially as it's similar to how wp background processing worked. I'll add this to the PR now.
