### ISSUE TITLE
The last modified date can sometimes be too strict and skip records that should be processed

### ISSUE THREAD

**Issue by jonathanstegall** [MinnPost/object-sync-for-salesforce#220]
**Describe the bug**

I've noticed that sometimes when we pull records, the plugin overzealously skips records because it thinks they've already been processed.

**To Reproduce**
Here's how I saw this happen:

1. Create a fieldmap that allows updated records to be pulled, but not created records.
2. Update a record that is already mapped in Salesforce so it should be updated in WordPress.
3. Create a new record in Salesforce that should not be created in WordPress.

In this scenario, WordPress will not have a newly created record (which is the correct behavior) but it will also not update the existing record (this is not correct behavior).

**Expected behavior**

The plugin should skip creating the record because that is not allowed. But it should update the existing record because that is allowed.

**Additional context**

Here's the code that causes this issue:

```php
if ( false === $pull_allowed ) {
	// update the current state so we don't end up on the same record again if the process fails
	if ( true === $this->batch_soql_queries ) {
		update_option( $this->option_prefix . 'pull_last_sync_' . $type, current_time( 'timestamp', true ) );
	} else {
		update_option( $this->option_prefix . 'currently_pulling_query_' . $type, $serialized_query );
		update_option( $this->option_prefix . 'last_pull_modified_date_' . $type, $result[ $salesforce_mapping['pull_trigger_field'] ] );
	}
	continue;
}
```

This is from salesforce_pull.php, starting in line 312.

**Comment by jonathanstegall** [comment]
I think the most obvious way to fix this is to expand the options that are being managed here. Instead of creating a last_pull_modified_date_type option, we should create one for each of the pull triggers. So a create, update, and delete. Then we can check for each of those to determine whether the current record can be pulled based on the trigger's date.

**Comment by jonathanstegall** [comment]
I think the way to work on this is to make a branch based off the 42 branch, since we have a method to check whether pull is allowed already.

**Comment by jonathanstegall** [comment]
Ugh this is stupid complicated. The current code works the way it does to keep the plugin from reprocessing records in case it fails in the middle of a SOQL query's loop. So the query has already been set at this point and when it is set, we don't know what trigger it's running (because that is set based on the Salesforce record's modified or created date).

An easy option might be to stop changing the query date when a record that is not allowed is processed, but only changing it after the loop finishes so it can still get other records in the loop. But this would break an important piece of functionality added some time ago and I think it's a bad idea.

I think there's got to be a way to handle this without changing that date.

**Comment by jonathanstegall** [comment]
This bug certainly doesn't happen in all instances of the situation I mentioned above. I think it happens when a scheduled task runs in the middle of those events.

**Comment by jonathanstegall** [comment]
Perhaps another option:

1. When a loop finishes, do what we currently do. I don't _think_ that is the problem.
2. But if we encounter a not allowed pull in the middle of the loop, rather than updating the timestamp and the serialized query, store the record's ID.
3. During the loop, check for that ID and if we find it, skip that record.
4. At the end of the loop, delete that option because step 1 overrides it.

I'm not convinced this would work, but it's possible.

**Comment by prowp** [comment]
Just to add some input, I'm definitely seeing record skipping happening with the plugin. I've rolled back to V 1.5.0 in hopes that it will stop skipping. I'm not sure if this is helpful but on today's batch, all of the records that were skipped had the same created/modified date and time. Records are set to up based on last modified date.

In a previous code set that I was using to sync before using this plugin, there were issues with timeouts on large queries. I added a stored option that recorded the last modified date into an option as each record was processed. This ensured that if the loop timed out, we could pull that recorded option date to restart the pull on the next go round. I didn't like writing an option with every loop, but it was very stable after that.

**Comment by jonathanstegall** [comment]
@prowp can you say more about your previous solution? If I'm understanding you correctly, the idea was like this:

1. Start a loop to process records modified in Salesforce (presumably the API call was to get all records since the last modified date?)
2. During each item in the loop, save the last modified date value (from Salesforce) as a `wp_options` value. (is it just one `wp_options` database field that gets updated after each record gets processed?)
3. If the loop fails for any reason, next time it would get records modified since the last modified date.

Am I understanding right here? Can you add that kind of detail?

**Comment by jonathanstegall** [comment]
@prowp sorry, now that I'm looking, can you indicate how this is different from the current behavior?

Right now. when modified records are pulled from Salesforce, it loops through them and during the loop it runs this code:

```
update_option( $this->option_prefix . 'currently_pulling_query_' . $type, $serialized_query );
update_option( $this->option_prefix . 'last_pull_modified_date_' . $type, $result[ $salesforce_mapping['pull_trigger_field'] ] );
```

The `last_pull_modified_date_Contact` option (for example) gets populated with the created or modified date of the Salesforce record (depending on whether it is new or existing).

Then each time the query runs, it uses that date value if it exists.

I feel like this is the same as what you're describing?

**Comment by jonathanstegall** [comment]
Another option to try:

1. When the loop starts, save the current timestamp value as the `last_pull_modified_date` option.
2. In each iteration of the loop, check for a `last_pull_id` option. If it matches the current `$result['Id']` value, skip it.
3. In each iteration of the loop, save the `$result['Id']` as the `last_pull_id` option value when it is successfully processed.

What this would mean:

1. Each time the query runs, it would load the `last_pull_modified_date` value, which would be the time the last query started. It would get all records modified since that time.
2. If a loop failed in the middle, it would have saved the result ID of the last successful record, and so it would not do any processing until that one was already passed.

**Comment by jonathanstegall** [comment]
We could save the current timestamp as the `last_pull_modified_date` value when the query ends, and keep the previous comment aside from that.

What this would mean:

1. Each time the query runs, it would be the time the last query ended. It would get all records modified since that time.
2. If a loop failed in the middle, it would have saved the result ID of the last successful record, so it would not do redundant processing.

If a long loop was processing and more records got modified, I'm not sure what would happen. I think that is probably the area to test for this method.

**Comment by jonathanstegall** [comment]
Okay, @prowp, if you've got the inclination, feel free to test the PR at #223. I'll try to do more testing and merge it in the next couple of days either way, but another pair of eyes is always welcome!

**Comment by jonathanstegall** [comment]
As of 69cde8872044ac14ef81389780f5320687f53a66 I think we have a much more robust solution for this bug. It both appears to keep the pull from skipping any records, and I think it will also preserve the offset that gets around Salesforce's refusal to respect the batchSize setting. However I need to see what it does when it gets above offset of 2000. I think it'll still work, but I need to see it.

**Comment by jonathanstegall** [comment]
So far the only possible issue I'm noticing is that whenever I close my laptop and then reopen it some time later, the pull temporarily looses the `offset` value for the SOQL query.

For example, it ran like this:

1. `ORDER BY LastModifiedDate ASC LIMIT 25 OFFSET 400`
2. `ORDER BY LastModifiedDate ASC LIMIT 25`
3. `ORDER BY LastModifiedDate ASC LIMIT 25 OFFSET 450`
4. `ORDER BY LastModifiedDate ASC LIMIT 25 OFFSET 475`

and so on.

I believe this happens because there's a transient that expired, although it's odd that it somehow goes right back to where it was supposed to be.

Perhaps if nothing else goes wrong, this could be released even if I can't find a fix for it, but I need to think more about that.

**Comment by jonathanstegall** [comment]
It could even be as simple as removing the transient expiration. I think at this point the checking is robust enough that we don't need to rely on the expiration. But again I need to test that.

**Comment by jonathanstegall** [comment]
Interestingly, the large batch I ran in the sandbox went like this:

(successful batch with offset of 2000)

```
[11-Jan-2019 19:22:27 UTC] PHP Notice:  Undefined variable: salesforce_mapping in /wp-content/plugins/object-sync-for-salesforce/classes/salesforce_pull.php on line 524
[11-Jan-2019 19:22:27 UTC] PHP Warning:  in_array() expects parameter 2 to be array, null given in /wp-content/plugins/object-sync-for-salesforce/classes/salesforce_pull.php on line 622
```

(next query with a refreshed modifieddate but no offset)

And in the logs, there was a query that ran with an error:

```
Exclude_from_current_campaign__c, Topics__c, Id, FROM Contact WHERE > 2019-01-11T19:22:27Z
```

So basically, it was omitting the lastmodifieddate but not the WHERE or the date, so the query failed.

**Comment by jonathanstegall** [comment]
The above issue with the ghost WHERE has also been resolved, but I forgot to note when it was resolved. Did a quick test to verify by lowering the max offset to 200. When the offset exceeds the max, it removes the offset and updates the lastmodifieddate value in the query.

**Comment by jonathanstegall** [comment]
There's a lot going on in this issue. I believe it's better to release it as part of the 1.6.0 release along with the initial set of REST API endpoints. Maybe will be a small delay for me to merge all of this and test the REST endpoints all over again, but I am inclined to think it's worthwhile.

**Comment by jonathanstegall** [comment]
I think I closed this too early. It appears to have trouble generating the subsequent queries.

**Comment by jonathanstegall** [comment]
I think 139a92b09d9e3a35589fba9fa52fc4f33c68a86b makes this much better. Also much easier to read.
