### ISSUE TITLE
Mapping Related list fields to ACF Repeater

### ISSUE THREAD

**Issue by Dssii3056** [MinnPost/object-sync-for-salesforce#221]
Hi Everyone,

I'm exploring this plugin, and I've gotten it to work just fine, but I have a question.

----

How would I go about mapping a list of related object fields in SF to WP using this plugin and Advanced Custom Fields?

----

For Example: If I want to map the Accounts* object in SF, which has 40 Contacts*, is there a way to do this using a repeater field in ACF?  Or would I have to create a custom object in SF with hundreds of fields and map them all manually using Object-Sync-for-Salesforce?

When I attempt to map to the repeater field, Object-Sync-for-Salesforce dropdown menu prompts me to map the field value to a specific 'row 0,1,2 in the repeater field.

Thank you for your assistance! Happy holidays =)

--Dan

**Comment by jonathanstegall** [comment]
Hi, please see issue #171. Currently, it's not possible to do what you're looking for within the plugin itself, although it might be possible with developer hooks.
