### ISSUE TITLE
set new post as published, Salesforce to WordPress

### ISSUE THREAD

**Issue by shaunw** [MinnPost/object-sync-for-salesforce#226]
**Describe the bug**
When a record is inserted/upserting from Salesforce to WordPress and creating a new record it is always as draft. Is there way to default this to publish (post_status) without creating a field in Salesforce to pass the publish value?

**Comment by jonathanstegall** [comment]
@shaunw yes. As you say, you could create a Salesforce field and map it. But also, you can use a developer hook like this:

```
add_filter( 'object_sync_for_salesforce_pull_params_modify', 'change_pull_params', 10, 6 );
function change_pull_params( $params, $mapping, $object, $sf_sync_trigger, $use_soap, $is_new ) {
	$params['post_status'] = 'publish';
	return $params;
}
```

**Comment by shaunw** [comment]
thanks for the quick response!
That filter doesn't seem to be working when pulling records from Salesforce and is causing a php error which is preventing all the fields from coming across.

`[22-Jan-2019 20:19:49 UTC] PHP Warning:  Illegal string offset 'method_modify' in [...]/wp-content/plugins/object-sync-for-salesforce/classes/wordpress.php on line 1164
[22-Jan-2019 20:19:50 UTC] PHP Warning:  Illegal string offset 'method_modify' in [...]/wp-content/plugins/object-sync-for-salesforce/classes/wordpress.php on line 1200
[22-Jan-2019 20:19:50 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function p() in [...]/wp-content/plugins/object-sync-for-salesforce/classes/wordpress.php:1201`

**Comment by jonathanstegall** [comment]
There's definitely a bug here. It was also reported in the [forums](https://wordpress.org/support/topic/draft-to-publish-issue/#post-11119479). I'll try to determine what's causing it and release a fix in the next while.

**Comment by jonathanstegall** [comment]
@shaunw apparently I had the wrong syntax for my own hook. See [the documentation](https://github.com/MinnPost/object-sync-for-salesforce/blob/master/docs/extending-parameters.md#salesforce-pull).

This hook should instead work like this:

```
add_filter( 'object_sync_for_salesforce_pull_params_modify', 'change_pull_params', 10, 6 );
function change_pull_params( $params, $mapping, $object, $sf_sync_trigger, $use_soap, $is_new ) {
	$params = array(
		'post_status' => array ( // wordpress field name
			'value' => 'publish',
			'method_modify' => 'wp_update_post',
			'method_read' => 'get_posts'
		)
	);
	return $params;
}
```

**Comment by jonathanstegall** [comment]
To be clear, if you change `@params` it will replace the entire array. In this case, you should add to the `$params` array a key for `post_status`. I updated my comment to reflect this.

**Comment by shaunw** [comment]
Thanks Jonathan! That did the trick. Great support! 👍 

You have an Amazon wishlist or something?

**Comment by jonathanstegall** [comment]
@shaunw thanks. The best way to support is through MinnPost, a nonprofit news org. You can do that [here](https://www.minnpost.com/support/?campaign=7010G0000012fXGQAY) if you like.
