### ISSUE TITLE
Issue with Authorize and Developer Account

### ISSUE THREAD

**Issue by andygagnon** [MinnPost/object-sync-for-salesforce#236]
Can't authorize connection with SFDC Developer Edition (not production, not sandbox).

Steps to reproduce behavior
I followed the instructions for setup on the salesforce and wordpress

1st Attempt,
for Login Base URL, tried,
https://test.salesforce.com
On authorize tab, clicked button,
Connect to Salesforce
Can't Log In with developer account.

2nd attempt,
for Login Base URL use developer account,
https://na40.lightning.force.com
On Authorize tab, clicked button,
Connected to Salesforce
Can Log In w/username, password
Asks for Authorization.  Works.
returns to WordPress,
Error 400: grant type not supported

**Expected behavior**
Connect WordPress with Salesforce.

Thanks for your time,
Andy

**Comment by jonathanstegall** [comment]
@andygagnon this sounds like you haven't granted the proper permissions to the app in Salesforce. It's also possible that the app in Salesforce isn't ready; sometimes it can take a few minutes.

**Comment by andygagnon** [comment]
Using the URL  https://login.salesforce.com  with a Lightning Developer account allowed me to authorize/connect.  Thanks!
