### ISSUE TITLE
Not allowed access to settings page

### ISSUE THREAD

**Issue by zacksmash** [MinnPost/object-sync-for-salesforce#241]
### Expected behavior
I should be able to see the settings page
### Actual behavior
I am shown a screen that says "Sorry, you are not allowed to access this page."
### Steps to reproduce behavior
New installation of WP
Add plugin from plugin directory
Click "Settings" from plugins list, underneath Object Sync for Salesforce

**Comment by jonathanstegall** [comment]
@zacksmash this issue is fixed in the current master branch. I’m hoping to release a new version this week that will contain the fix.

**Comment by jonathanstegall** [comment]
(Duplicate with #239)

**Comment by jonathanstegall** [comment]
I'm releasing the new version that includes this fix right now. Sorry it took longer than I'd hoped.
