### ISSUE TITLE
Error during authorization

### ISSUE THREAD

**Issue by zacksmash** [MinnPost/object-sync-for-salesforce#244]
**Describe the bug**
Trying to authorize via the plugin and I'm getting a "Site can't be reached" error in Chrome.

**To Reproduce**
1. Enter all information on settings tab, save
2. Go to Authorize tab, click authorize
3. Chrome shows a "Site can't be reached" error.

**Expected behavior**
I assume this is the step that takes me to Salesforce login screen, so that's what I'd expect to see.

**Environment (please complete the following information):**
 - WordPress Version: 5.1.1
 - Other relevant plugins: ACF
 - PHP Version 7.2

**Comment by jonathanstegall** [comment]
Please list the values you are using for the settings, with the exception of consumer key/secret. Probably the login or callback URL is not what the plugin expects.

**Comment by zacksmash** [comment]
<img width="1551" alt="Screen Shot 2019-03-12 at 8 48 34 PM" src="https://user-images.githubusercontent.com/6118407/54250136-3b646180-4508-11e9-9c25-a016e49918b6.png">

**Comment by jonathanstegall** [comment]
Okay. What's the exact URL where Chrome gives you the error after you click the authorize button? Clicking the button should take you to https://login.salesforce.com, if your callback URL is the full URL listed below it.

**Comment by zacksmash** [comment]
https://login.salesforce.com/services/oauth2/authorize?response_type=code&client_id=MY_CLIENT_ID&redirect_uri=https://salesforce.test/wp-admin/options-general.php?page=object-sync-salesforce-admin&tab=authorize

**Comment by zacksmash** [comment]
So, I think it just wasn't registering my callback URL, that error seems to have disappeared.

Now, when it redirects me back to my application, it still says I need to authorize. It doesn't seem to send the access token with it.

**Comment by jonathanstegall** [comment]
What it should do, after you authorize it in Salesforce, is end up at /wp-admin/options-general.php?page=object-sync-salesforce-admin&tab=authorize and then it should reload the page. Sometimes there's a lag on the reload, but if it was able to authorize with Salesforce it will reload and then you'll see this.

![image](https://user-images.githubusercontent.com/435342/54250661-aadf4e80-4512-11e9-8429-2240db3d35e5.png)

Now if it's never doing that reload, there may be a browser error that you can see in the console. It's also possible that the Salesforce app hasn't finished initializing itself. That isn't usually the error that happens while it's waiting to initialize, but it's also never a helpful error.

**Comment by zacksmash** [comment]
Okay, I think I'm all set now. Thanks very much, I really appreciate your help.
