### ISSUE TITLE
Update Data in Wordpress Requires Saving SalesForce ObjEct twice

### ISSUE THREAD

**Issue by thebananaland** [MinnPost/object-sync-for-salesforce#258]
### Expected behavior
When I make a modification to the object in salesforce to update all mapped fields in wordpress
### Actual behavior
When I make a modification to the object in salesforce the first time doesn't update all fields. However if that wordpress object had already been modified by the object sync plugin all fields are updated properly. 
### Steps to reproduce behavior
Find a object in salesforce that hasn't been modified yet since the object sync plugin was setup in wordpress. Update the salesforce object. No Error, but content isn't fully updated. Update same salesforce object again, and everything works as expected.

**Comment by jonathanstegall** [comment]
Please describe how your fieldmap works: exactly which objects are mapped to which objects and which fields are mapped.

Also, please describe any error logs that you have in WordPress or on your server. You may need to turn on debug mode.

**Comment by thebananaland** [comment]
Hi Jonathan,

Thanks so much for the fast response. I’d be happy to give you direct access to our setup if that is easier for you, let me know.

I’m mapping product objects to a custom post type name Product in wordpress. All of the fields being mapped are ACF fields with the exception of a few custom taxonomy terms.

No current error logs on the server. I do occasionally get an error under the plugins logs. I’ve pasted it below:

Error: WordPress update for product ID 3116 was unsuccessful with these errors:
Array
(
    [0] =&gt; Array
        (
            [key] =&gt; compartments
            [value] =&gt; Array
                (
                    [value] =&gt; 1
                    [method_modify] =&gt; update_post_meta
                    [method_read] =&gt; get_post_meta
                )

        )

    [1] =&gt; Array
        (
            [key] =&gt; volume
            [value] =&gt; Array
                (
                    [value] =&gt; 91.3
                    [method_modify] =&gt; update_post_meta
                    [method_read] =&gt; get_post_meta
                )

        )

    [2] =&gt; Array
        (
            [key] =&gt; container_id_length_d
            [value] =&gt; Array
                (
                    [value] =&gt; 8.4375
                    [method_modify] =&gt; update_post_meta
                    [method_read] =&gt; get_post_meta
                )

        )

    [3] =&gt; Array
        (
            [key] =&gt; container_id_width_d
            [value] =&gt; Array
                (
                    [value] =&gt; 8.4375
                    [method_modify] =&gt; update_post_meta
                    [method_read] =&gt; get_post_meta
                )

        )

    [4] =&gt; Array
        (
            [key] =&gt; container_id_height_d
            [value] =&gt; Array
                (
                    [value] =&gt; 2.875
                    [method_modify] =&gt; update_post_meta
                    [method_read] =&gt; get_post_meta
                )

        )

    [5] =&gt; Array
        (
            [key] =&gt; container_od_length_d
            [value] =&gt; Array
                (
                    [value] =&gt; 9.375
                    [method_modify] =&gt; update_post_meta
                    [method_read] =&gt; get_post_meta
                )

        )

    [6] =&gt; Array
        (
            [key] =&gt; container_od_width_d
            [value] =&gt; Array
                (
                    [value] =&gt; 9.375
                    [method_modify] =&gt; update_post_meta
                    [method_read] =&gt; get_post_meta
                )

        )

    [7] =&gt; Array
        (
            [key] =&gt; container_od_height_d
            [value] =&gt; Array
                (
                    [value] =&gt; 3
                    [method_modify] =&gt; update_post_meta
                    [method_read] =&gt; get_post_meta
                )

        )

    [8] =&gt; Array
        (
            [key] =&gt; case_pack
            [value] =&gt; Array
                (
                    [value] =&gt; 100
                    [method_modify] =&gt; update_post_meta
                    [method_read] =&gt; get_post_meta
                )

        )

    [9] =&gt; Array
        (
            [key] =&gt; net_weight_ncm
            [value] =&gt; Array
                (
                    [value] =&gt; 12.2
                    [method_modify] =&gt; update_post_meta
                    [method_read] =&gt; get_post_meta
                )

        )

    [10] =&gt; Array
        (
            [key] =&gt; pallet_#_cartons_layer
            [value] =&gt; Array
                (
                    [value] =&gt; 8
                    [method_modify] =&gt; update_post_meta
                    [method_read] =&gt; get_post_meta
                )

        )

    [11] =&gt; Array
        (
            [key] =&gt; product_line_relationship
            [value] =&gt; Array
                (
                    [value] =&gt; 428
                    [method_modify] =&gt; update_post_meta
                    [method_read] =&gt; get_post_meta
                )

        )

    [12] =&gt; Array
        (
            [key] =&gt; carton_id_length
            [value] =&gt; Array
                (
                    [value] =&gt; 18.8125
                    [method_modify] =&gt; update_post_meta
                    [method_read] =&gt; get_post_meta
                )

        )

    [13] =&gt; Array
        (
            [key] =&gt; carton_id_width
            [value] =&gt; Array
                (
                    [value] =&gt; 11
                    [method_modify] =&gt; update_post_meta
                    [method_read] =&gt; get_post_meta
                )

        )

    [14] =&gt; Array
        (
            [key] =&gt; carton_id_height
            [value] =&gt; Array
                (
                    [value] =&gt; 18.5
                    [method_modify] =&gt; update_post_meta
                    [method_read] =&gt; get_post_meta
                )

        )

)

**Comment by jonathanstegall** [comment]
No, I don’t need server access; we’re not able to offer that level of support.

I’ve used ACF some with this plugin though, and here’s what I can tell you:

1. If the Salesforce object has a required field that is mapped to an ACF field, it can fail to create the record because the way WordPress works is it creates the record and then it creates the meta fields. Salesforce doesn’t work this way so it can cause errors.
2. If this is the issue, there’s not much you can do beyond changing the required field mapping. It doesn’t always happen like this but when it does, that’s the only fix I have.

**Comment by jonathanstegall** [comment]
I was reading that backwards. You're talking about the WordPress object not being updated when the Salesforce object is updated. I'm not sure I've seen that before. It may still have something to do with that, or it may be an ACF issue. ACF is non-standard in some ways. You should make sure your install of this plugin is updated, as sometimes there are fixes for these kind of things.

Aside from that, if you can do some error logging and determine exactly where the issue is, and/or submit a pull request if you can determine what a fix would be, it would help, but I'll investigate further when I can.

**Comment by thebananaland** [comment]
Thanks Jonathan. I’ll do some further investigation all day tomorrow to identify which field could be causing the issue.

**Comment by jonathanstegall** [comment]
From the error message it seems like you might have been running an older plugin version. If so I’d start with updating and see if the logs get any better.

**Comment by thebananaland** [comment]
Hi All, So still stumped here. I've updated to latest/greatest version and have done hours of debugging. What i'm seeing is that the first "sync" or mapping to the wordpress object isn't working. For background the objects already exist in wordpress and I'm using upsert to match the title of the salesforce object to the title of the wordpress object. 

After this inital "mapping" failure all additional syncs work perfectly.

**Comment by jonathanstegall** [comment]
@thebananaland it's interesting that the objects already exist in WordPress. Technically this plugin doesn't support syncing of pre-existing data. At least not intentionally.

I think it would be nice if we could support that in a robust way, but it's fairly complicated (as this would suggest, if that is the reason for the issue you're seeing) and I certainly don't have any schedule for that kind of work.

I'm interested to see what happens if you try syncing data that doesn't previously exist. Do you have the same issues, or does it work more as expected?

**Comment by thebananaland** [comment]
Gotcha that would explain it.  I’ll take a look and see if I can work on some code to accommodate existing wordpress objects… Thinking maybe a simple check if a wordpress post exists using the field selected as prematch.

But in the mean time as a current workaround if I deleted all of my wordpress “product” posts what would be the best way to do a bulk trigger on salesforce to force a sync on all of the objects in salesforce that I need added back to wordpress?


Best,
Jordan Rabidou
------------------------
The Bananaland
162 Elm St.
Bridgeport CT. 06604
(203) 244-8345

**Comment by jonathanstegall** [comment]
@thebananaland I'm not sure there's a reliable way to do that if all of the Salesforce objects already exist.

One thing you could consider, if you're already thinking about writing code, is this:

1. Find the Salesforce IDs that you want to map into WordPress.
2. Find the WordPress product post IDs you want to map to them.
3. Do a bulk SQL import into the object map table in WordPress.

For example, that table could take rows like this:

```
INSERT INTO `wp_object_sync_sf_object_map` (`wordpress_id`, `salesforce_id`, `wordpress_object`, `created`, `object_updated`, `last_sync`, `last_sync_action`, `last_sync_status`, `last_sync_message`)
VALUES
	('8311', '003F000001TYaS9IAL', 'user', '2019-04-16 00:00:00', '2019-04-16 00:00:00', '2019-04-16 00:00:00', 'push', 1, 'manual import');
```

It's possible that if you were able to do this, you could run a bulk update in Salesforce, and then the plugin would (hopefully) pull in any data from Salesforce that it didn't have.

I think that is more likely to give a good result than deleting existing posts, but your mileage may vary of course.
