### ISSUE TITLE
Missing Salesforce ID and mapping when using object_sync_for_salesforce_push_success

### ISSUE THREAD

**Issue by mistermarco** [MinnPost/object-sync-for-salesforce#278]
**Describe the bug**
I'm trying to use the object_sync_for_salesforce_push_success action to retrieve the Salesforce ID after a successful push. In my case, $op = Create. 

The [docs](https://github.com/MinnPost/object-sync-for-salesforce/blob/08ed14232a445aa6f52a7651bd7315beec3e1742/docs/extending-before-and-after-saving.md#after-success-1) suggest that the last parameter ($object_id) is the Salesforce object ID, but I think it's [actually the name of the WordPress ID field](https://github.com/MinnPost/object-sync-for-salesforce/blob/fa15fc9ac414dd80d02bd1d2c12f3ef0d337e455/classes/salesforce_push.php#L1053).

In addition, the mapping object ($object_sync['mapping_object']) is blank, even though it's available [right before the call to do_action](https://github.com/MinnPost/object-sync-for-salesforce/blob/fa15fc9ac414dd80d02bd1d2c12f3ef0d337e455/classes/salesforce_push.php#L1048).

**To Reproduce**
1.  Map a WordPress object to a Salesforce object
2. Add the [example code](https://github.com/MinnPost/object-sync-for-salesforce/blob/08ed14232a445aa6f52a7651bd7315beec3e1742/docs/extending-before-and-after-saving.md#after-success-1) to a custom plugin (NOTE: update the $accepted_args value from 3 to 4).
3. Modify the code to include a wp_mail call similar to: 
`wp_mail('your email', $op . ' - ' . $object_id, print_r($synced_object, true));`
4. Create a new object in WordPress
5. Notice email has 'ID' as the value of the $object_id, and the $synced_object['mapping_object'] is empty.

**Expected behavior**
Ideally, $object_id is set to the Salesforce ID, and the mapping_object is avaliable.

**Environment (please complete the following information):**
 - WordPress Version: 5.2.2
 - PHP Version: 7.1
 - Plugin Version: 1.8.6

**Comment by jonathanstegall** [comment]
This issue is closed by pull request #279.
