### ISSUE TITLE
Update ActionScheduler to 3.2

### ISSUE THREAD

**Issue by jonathanstegall** [MinnPost/object-sync-for-salesforce#299]
**Is this update related to a problem? Please describe.**
ActionScheduler 3.0 is solving a lot of problems they've defined. I'm hoping to find some documentation about it, and especially what the upgrade process is like, since it has been released. https://github.com/woocommerce/action-scheduler

**Current version the plugin includes**
Ex. ActionScheduler 2.2.5

**Version to be included**
Ex. ActionScheduler 3.2.0 (unless there are updates before I get to it)

**Have you tested this update? What happened?**
Not yet

**Additional context**
It's worth noting that this upgrade does create new custom tables. It's possible we need to put it in a version 2.0.0, but I am not really sure if it warrants that.

**Comment by jonathanstegall** [comment]
It seems like this is different enough that we should go ahead and make a version 2.0.0 for it.

**Comment by afgarcia86** [comment]
Did we lose the "ActionScheduler" menu recently? I am noticing a lot of DB usage on these tables. Hoping there is an easy way to flush it.

**Comment by jonathanstegall** [comment]
@afgarcia86 no, the Scheduled Actions screen is still there. You can (as long as you have permission) access it at the `/wp-admin/tools.php?page=action-scheduler` URL.

**Comment by afgarcia86** [comment]
Weird its not showing up in the UI for me anymore but I can get to it with your link. Must be something with my theme. Thanks for sharing that 😓

**Comment by jonathanstegall** [comment]
I've added a new branch that does nothing but upgrade ActionScheduler to 3.1.x. For however long there's a testing period, I'll make sure to merge any changes to the main branch into this branch to make sure it stays up to date.

Pull request can be tracked at: #395. Mention any issues in there.
