### ISSUE TITLE
The plugin is unable to access any Salesforce objects for object mapping

### ISSUE THREAD

**Issue by alexeympw** [MinnPost/object-sync-for-salesforce#329]
Field mapping broke 2 weeks ago and now there is no way to select salesforce object

I have created field mapping in September 2019 it worked fine all data was transferring fine
Today I found many Errors 403 in Logs (http://joxi.ru/KAgJpwNsEjk8p2) it started to create 2 weeks ago 21 October
I go to filed mapping and found errors, all my fields for mapping now not connected to WordPress fields.
Error screen: http://joxi.ru/VrweOkRs7bdyN2
Error screen: http://joxi.ru/brRn4wBu7Mk9pr
I already update all APP keys and update app permission but my fields still not fount salesforce mapping objects.

I tried to create a new app and connect it but the result still the same.
I tried to change the API version to 47 winter 20 but the result still the same.

WordPress version 5.2.4

PHP Version 7.2

**Comment by jonathanstegall** [comment]
This is certainly an issue in Salesforce, and not with this plugin. I'm far from a Salesforce permissions expert, but here's a possible solution a quick Google search turned up: https://developer.salesforce.com/forums/?id=906F00000009AA8IAM

**Comment by jonathanstegall** [comment]
Also, when you posted the first link, http://joxi.net/KAgJpwNsEjk8p2, you should click on each of those log entries and see what the error messages say. Salesforce doesn't always return helpful error messages, but sometimes it does and the plugin tries to log whatever Salesforce returns.

**Comment by alexeympw** [comment]
@jonathanstegall Yes, you're probably right. This is not a bug.

Log report says it API limits: http://joxi.ru/a2XYpwLswMLngA

I already disabled cron but it not helps. Sync works are very often http://joxi.ru/bmobpl5I3k0p4r

Plugin and WordPress continue the sync. I made **Pull throttle** (option) is very large but it does not help http://joxi.ru/LmGpxwbIwKdxj2
