### ISSUE TITLE
I can't pull from Salesforce

### ISSUE THREAD

**Issue by cedche99** [MinnPost/object-sync-for-salesforce#349]
**Describe the bug**
I can't pull from Salesforce

**Expected behavior**
When creating or updating in Salesforce, there must be a creation or modification in WP

**Screenshots**
![Capture d’écran 2020-03-27 à 17 03 45](https://user-images.githubusercontent.com/12508260/77775549-fa74b780-704c-11ea-9903-239fa8bd2bd9.png)

**Environment (please complete the following information):**
 - WordPress Version: 5.3.2
 - ACF
 - CPT UI
 - object-sync-for-salesforce Version : 1.9.0

**Additional context**
When i push from WP, modification or creation is done on Salesforce

**Comment by jonathanstegall** [comment]
For a bug like this, you need to provide a lot more information. Start with [the troubleshooting document](https://github.com/MinnPost/object-sync-for-salesforce/blob/master/docs/troubleshooting.md).

**Comment by cedche99** [comment]
I solved the problem by installing the plugin: https://fr.wordpress.org/plugins/wp-crontrol/
