### ISSUE TITLE
Question: Does this support Salesforce Community Cloud?

### ISSUE THREAD

**Issue by benlk** [MinnPost/object-sync-for-salesforce#361]
https://www.salesforce.com/products/community-cloud/features/

**Describe the solution you'd like**
Ideally, it would be possible to one-way sync data from Salesforce Community Cloud to WordPress.

**Describe alternatives you've considered**
Nothing yet, purely research-gathering at this time.

**Additional context**
A member was asking for a solution for their problem, and we were wondering whether this would work for them.

**Comment by jonathanstegall** [comment]
I am not familiar with community cloud at all. But here are the questions I think we would need to answer:

1. Is it accessible via the REST API or SOAP? If neither of those have access to it, this plugin won't currently be able to integrate with it.
2. If it is accessible from either of those, is it made up of the basic pattern of objects and fields that are stored on those objects?

If it is accessible via dev tools, and the basic data storage is that it creates objects and then stores fields on those objects, I think this plugin should be able to support it.

**Comment by benlk** [comment]
These are good questions, and if that project continues I'll remember this issue. But for now, it's safe to close this issue and think no more about it.
