### ISSUE TITLE
Failure to log in to Wordpress after authorization

### ISSUE THREAD

**Issue by danitamtd** [MinnPost/object-sync-for-salesforce#366]
**Describe the bug**
Cannot log in to Wordpress after clicking on "Connect to Salesforce" under Authorize tab. 

Was redirected to Salesforce which I successfully logged into and allowed access to the app. However, I'm stuck on the WP login page. There are no error messages, it simply won't redirect me anywhere after clicking on "Log In".

**To Reproduce**
1. Go to the Authorize tab
2. Click on 'Connect to Salesforce'
3. Log in to salesforce and allow app access
4. Log in to Wordpress

**Expected behavior**
I should be able to enter my Wordpress credentials, redirected to the plugin tab and successfully authorize the plugin.

**Additional context**
I am able to log into Wordpress with no issue using the usual log in page. The problem only occurs when trying to authorize the app.

**URL where issue lies**
https://**mysite**/wp-login.php?redirect_to=https%3A%2F%2F**mysite**%2F%2Fwp-admin%2Foptions-general.php%3Fpage%3Dobject-sync-salesforce-admin%26tab%3Dauthorize%26code%3DaPrxshT49BthlzJJwN.5fZSdJaCct7r.OiBC7QHwQza1iSSV8c_Ha8u89KufPS69KckVPNigvw%253D%253D&reauth=1

**Comment by jonathanstegall** [comment]
Check the troubleshooting page in the documentation. https://github.com/MinnPost/object-sync-for-salesforce/blob/master/docs/troubleshooting.md

**Comment by danitamtd** [comment]
Thanks for your reply Jonathan. We got the issue fixed.

**Comment by jonathanstegall** [comment]
Glad to hear it. For future reference, this kind of thing is the purpose of the WordPress support forums.
