### ISSUE TITLE
Salesforce Master-detail field value are not syncing from WordPress

### ISSUE THREAD

**Issue by vigneshbabuor** [MinnPost/object-sync-for-salesforce#368]
Hi There,

I have mapped a Salesforce master-detail relationship field with WordPress custom post type field. it is not syncing and i am getting a mapping error. I am not able to add screenshots here. Please take as a new issue.

Scenario:

I have mapped below 3 fields in WordPress custom post - 
1. Start_Date_and_Time__c - date time field
2. End_Date_and_Time__c - date time type field
3. Order__c - master-detail relation field

Action : when i create a post with above fields in WordPress it should be upsert with Salesforce.

 But i am getting below debug error message:
<p>Object: Order_Time_Slot__c</p><p>Message: Required fields are missing: [Order__c]</p><p>Params: Array
(
    [Start_Date_and_Time__c] =&gt; 2020-10-14T12:00:00+10:00
    [End_Date_and_Time__c] =&gt; 2020-10-14T16:00:00+10:00
)
</p>

**Comment by jonathanstegall** [comment]
You need to figure out why the Order__c field is not coming through. You might need to inspect your Salesforce installation and see what it's called when the REST API sends data. For example it might be Order__c.Id instead.

**Comment by jonathanstegall** [comment]
I'm noticing that you also added this to the plugin support forum, so I will post this answer there. As this is a duplicate, and is a support issue, I'm closing it as a GitHub issue.
