### ISSUE TITLE
'Salesforce Field Display Value' - API Name setting not applying all the time.

### ISSUE THREAD

**Issue by CodeZeno** [MinnPost/object-sync-for-salesforce#377]
When I edit an existing Fieldmap and add another field mapping, the Salesforce Field dropdown list differs from the dropdown list of existing fields.

Existing fields show a list of the API Names (expected because I have the 'Salesforce Field Display Value' setting set to API Name)
The new field shows a list of Field Labels.

It seems 'Salesforce Field Display Value' setting is not being applied to new fields.

**To Reproduce**
1. Create a Fieldmap with some fields and save
2. Edit the Fieldmap and add a new field
3. Compare the list of options for the 'Salesforce Field' for an existing field and the one you just added.

**Expected behaviour**
I expect the lists to match

**Environment (please complete the following information):**
 - WordPress Version: 5.6.1
 - Other relevant plugins: Advanced Custom Fields
 - PHP Version: 7.3.27

**Comment by jonathanstegall** [comment]
@CodeZeno thank you for reporting this. I'll try to get a small release with a fix out quickly.
