### ISSUE TITLE
Fatal error upgrading from 1.9.6 to 1.9.8

### ISSUE THREAD

**Issue by modelm** [MinnPost/object-sync-for-salesforce#382]
**Describe the bug**
Fatal error during/after upgrade from 1.9.6 to 1.9.8.

**To Reproduce**
1. Install version 1.9.6
2. Visit the plugins page in the dashboard and update the plugin
3. The site becomes stuck in maintenance mode and the plugin throws a fatal error until deleted/deactivated manually.

**Expected behavior**
No fatal error.

**Screenshots**

**Environment (please complete the following information):**
 - WordPress Version: 5.6.2
 - Other relevant plugins N/A
 - PHP Version 7.3.26

```
PHP Warning:  require_once(/app/wordpress/wp-content/plugins/object-sync-for-salesforce/classes/class-object-sync-sf-queue.php): failed to open stream: No such file or directory in /app/wordpress/wp-content/plugins/object-sync-for-salesforce/object-sync-for-salesforce.php on line 250
Warning: require_once(/app/wordpress/wp-content/plugins/object-sync-for-salesforce/classes/class-object-sync-sf-queue.php): failed to open stream: No such file or directory in /app/wordpress/wp-content/plugins/object-sync-for-salesforce/object-sync-for-salesforce.php on line 250
PHP Fatal error:  require_once(): Failed opening required '/app/wordpress/wp-content/plugins/object-sync-for-salesforce/classes/class-object-sync-sf-queue.php' (include_path='.:/usr/local/lib/php') in /app/wordpress/wp-content/plugins/object-sync-for-salesforce/object-sync-for-salesforce.php on line 250
Fatal error: require_once(): Failed opening required '/app/wordpress/wp-content/plugins/object-sync-for-salesforce/classes/class-object-sync-sf-queue.php' (include_path='.:/usr/local/lib/php') in /app/wordpress/wp-content/plugins/object-sync-for-salesforce/object-sync-for-salesforce.php on line 250
Error: There has been a critical error on this website.Learn more about debugging in WordPress. There has been a critical error on this website.
```

**Comment by jonathanstegall** [comment]
Thank you for reporting this. I've set up a blank WordPress site, installed and activated version 1.9.6, and then upgraded to 1.9.8 without this happening. Can you give me some more info? What host are you using? And do you have file access to tell whether the `classes/class-object-sync-sf-queue.php` in fact does not exist? This file hasn't changed in some time, so I'm not sure what could've happened, unless the plugin failed to finish downloading during the upgrade process.

**Comment by modelm** [comment]
The file does exist in the downloaded plugin in `/upgrade/` after I manually deactivated the old version and disabled maintenance mode:

```
$ ls -l ../../upgrade/object-sync-for-salesforce.1.9.8-m34Ddg/object-sync-for-salesforce/classes/
total 976
-rw-r--r--@ 1 ryan  staff   9786 Feb 22 10:50 activate.php
-rw-r--r--@ 1 ryan  staff   1487 Feb 22 10:50 admin-notice.php
-rw-r--r--@ 1 ryan  staff  89435 Feb 22 10:50 admin.php
-rw-r--r--@ 1 ryan  staff   9163 Feb 22 10:50 class-object-sync-sf-queue.php
-rw-r--r--@ 1 ryan  staff   6618 Feb 22 10:50 class-object-sync-sf-rest.php
-rw-r--r--@ 1 ryan  staff   4443 Feb 22 10:50 deactivate.php
-rw-r--r--@ 1 ryan  staff  18748 Feb 22 10:50 logging.php
-rw-r--r--@ 1 ryan  staff  41013 Feb 22 10:50 salesforce.php
-rw-r--r--@ 1 ryan  staff  43053 Feb 22 10:50 salesforce_mapping.php
-rw-r--r--@ 1 ryan  staff  92002 Feb 22 10:50 salesforce_pull.php
-rw-r--r--@ 1 ryan  staff  57203 Feb 22 10:50 salesforce_push.php
-rw-r--r--@ 1 ryan  staff   2390 Feb 22 10:50 salesforce_query.php
-rw-r--r--@ 1 ryan  staff   3055 Feb 22 10:50 salesforce_soap_partner.php
-rw-r--r--@ 1 ryan  staff  92674 Feb 22 10:50 wordpress.php
```

However the previous version, still active at that point during the upgrade, does not include a `classes` directory at all:
```
$ ls -l ../../plugins/object-sync-for-salesforce/
total 136
drwxr-xr-x@ 29 ryan  staff    928 Feb 22 10:51 docs/
drwxr-xr-x@  3 ryan  staff     96 Jan 15 07:06 languages/
-rw-r--r--@  1 ryan  staff  15143 Jan 15 07:06 license.txt
-rw-r--r--@  1 ryan  staff  21994 Jan 15 07:06 object-sync-for-salesforce.php
-rw-r--r--@  1 ryan  staff  26478 Jan 15 07:06 readme.txt
drwxr-xr-x@  3 ryan  staff     96 Jan 15 07:06 templates/
drwxr-xr-x@  8 ryan  staff    256 Jan 15 07:06 vendor/
```

I installed the plugin at version 1.9.6 initially via `wp plugin install --activate object-sync-for-salesforce` and never had issues until trying to upgrade. The readme.txt does confirm it's for version 1.9.6 but I can't explain how or why it's missing files. If I download the release from github I see the classes directory included, and I also see that in the SVN from the wordpress.org plugin directory.

My best guess is the plugin was somehow partially upgraded and some unrelated problem interrupted the process leaving files half-copied? I'm not familiar enough with the WP internals in that regard to say more, but it does seem like both release versions contain that file so I don't know why my install does not.

**Comment by jonathanstegall** [comment]
Yeah, I think it had to be a download that failed before getting all of the files, for some reason. The plugin has always had a classes directory, at least as far as I can remember. In 1.9.7, which was only live for a couple of minutes, there was a missing file from inside the `vendor` directory, but that doesn't seem to be what you're experiencing here and I don't think it would have affected 1.9.8's download, in any case.

**Comment by modelm** [comment]
Thanks for the quick response and info! I'll go ahead and close this since both versions include that file and you couldn't reproduce it, I'll just delete & reinstall for now. If I get more info in the future I'll reopen.
