### ISSUE TITLE
Validation - Prevent Duplicate Field Mappings / Sorting of Mapped Fields

### ISSUE THREAD

**Issue by TornMarketing** [MinnPost/object-sync-for-salesforce#387]
**Is your feature request related to a problem? Please describe.**
Currently when mapping fields, there is the risk of adding in duplicate mapped fields, this results in the functionality not triggering with no error logs.
We have a data set of over 200 fields, easily gets lost.

**Describe the solution you'd like**
Validation message highlighting that the field has already been mapped.

**Describe alternatives you've considered**
Sort order of mapped fields on either field type, WP field, SF API field name

**Additional context**

**Comment by jonathanstegall** [comment]
This is a good feature. It's not trivial, but I think it'd be great to add it at some point.

**Comment by jonathanstegall** [comment]
@TornMarketing I'm working on preparing a version 2.0.0 of this plugin for release. One way that I thought we could unobtrusively address this is to add `disabled` to the `option` for a field if it has already been used. This way, if the Salesforce field or the WordPress field has already been mapped, it can't be mapped again.

I'm wondering if this would address the problem you've encountered when you have a lot of fields. I was thinking that I had previously mapped the same field more than once, but now that I think about it maybe I haven't, and if you've already seen that it doesn't work, it seems worth addressing. If you think this would solve the problem, I wonder if you'd be willing to test my JavaScript change to see if it's worth adding to this next version. I'll add it as a pull request and link it here if you'd be open to that.

**Comment by jonathanstegall** [comment]
Note to self: I'm inclined to put this in as an option on the settings screen, alongside the other fieldmap settings.

<img width="984" alt="/wp-admin/options-general.php?page=object-sync-salesforce-admin screenshot" src="https://user-images.githubusercontent.com/435342/125639941-4dcdeb7d-3239-4a27-9c1d-587acaf65846.png">

This way users could turn it on if it works for them, and if it has any unforeseen consequences, or if they don't need that visual, they could leave it turned off.

**Comment by jonathanstegall** [comment]
<img width="1230" alt="screenshot with this fix in place as a setting" src="https://user-images.githubusercontent.com/435342/125673305-38c32d58-c72f-48fa-bc08-f2bc2b6a3c52.png">

**Comment by jonathanstegall** [comment]
At least for the purpose of v2.0.0, I'm going to go ahead and close this issue. If it turns out that we need to do more significant emphasis on this in a later release, I think that's fine, but it would require more thought to do it well and it should be part of a bigger interface design change.
