### ISSUE TITLE
New Option to Disable Already Used Mapping Fields is Stuck On

### ISSUE THREAD

**Issue by timnolte** [MinnPost/object-sync-for-salesforce#415]
**Describe the bug**
The new plugin setting that disables the reuse of already mapping WordPress and Salesforce fields seems to be stuck always on. Setting this flag on the plugin options screen has no affect and already mapped fields are always disabled. Note that we also have the

**To Reproduce**
1. Ensure the new "Prevent Duplicate Field Mapping?" option is unchecked.
2. Add/edit a Field Mapping.
3. Map some WordPress fields to Salesforce.
4. Save & reload the Field Mapping.
5. Fields already mapped are disabled and cannot be selected.

**Expected behavior**
If the option "Prevent Duplicate Field Mapping?" is not enabled, or disabled again after having been enabled editing a field mapping should allow WordPress and Salesforce fields to be mapped again.

**Screenshots**
https://imgur.com/a/Kzlp4ol
https://imgur.com/a/BihAV4Q

**Environment (please complete the following information):**
 - WordPress Version: 5.7.2
 - Object Sync Plugin: 2.0.1
 - Other relevant plugins:
  - ACF 5.9.5
  - Gravity Forms 2.4.23
  - The Events Calendar 5.4.0.2
 - PHP Version: 7.4

**Comment by jonathanstegall** [comment]
Sigh. Thanks, @timnolte. I think this is fixed in #416, if you have a minute to test. I'll get this released today or tomorrow, otherwise.
