### ISSUE TITLE
Feature Request: Active/Inactive flag on a field mapping

### ISSUE THREAD

**Issue by TornMarketing** [MinnPost/object-sync-for-salesforce#422]
Feature Request: Active/Inactive flag at a field mapping specific level

Ability to configure a field mapping in a deactivated state, or turn off syncs whilst handling configurations etc 
Allowing to configure within a production environment whilst not disrupting business as usual

Ability to have all imports come in default to be inactive

**Comment by jonathanstegall** [comment]
@TornMarketing If I'm understanding you correctly, these are related things. That is, you'd want the ability to set a fieldmap to inactive and then you'd want the ability to set imported fieldmaps to be inactive when they're imported. Is that correct?
