### ISSUE TITLE
Custom post type some fields are not displaying

### ISSUE THREAD

**Issue by mansoorbilalrana** [MinnPost/object-sync-for-salesforce#427]
Hi, 

I have a WordPress website where I mapped the custom post type fields with sales force using this plugin. Custom post type has taxonomies. In taxonomy we are creating custom fields. In object sync plugin field mapping  when I select the listing it display custom fields in dropdown list but some custom fields are missing. 

For example 
I have deals listing type in which I have custom fields like dispensary-deal-page, menu, job_tags. dispensary-deal-page and menu, are displayed in field map drop down list but  job_tags is missing. Like this some other fields are also not listed in the drop down.
The fields are existed in database before I installed the plugin so there is no fields cache issue.

Can you please tell me which thing I am missing.

Thanks

**Comment by mansoorbilalrana** [comment]
@jonathanstegall

**Comment by jonathanstegall** [comment]
This is not the place for support requests.

**Comment by mansoorbilalrana** [comment]
Okay, Sorry I am closing the issue.
