### ISSUE TITLE
Plugin not creating WP User object

### ISSUE THREAD

**Issue by social-ink** [MinnPost/object-sync-for-salesforce#446]
The plugin successfully maps fields and syncs both ways on field data, but when creating a user in SF, that user never gets created in WP, despite all settings (apparently?) working fine.  It had been working about 2 years ago when we inherited this site from a different developer, but this is no longer working. Any guidance or things to check would be helpful. Logs don't show anything that needs attention (that I can see). Thanks in advance.

Plugin version 2.0.3
WP 5.8.2
SF API - Winter '22 (53)

**Comment by jonathanstegall** [comment]
This is not the place for support requests. You can add a question to the WordPress support forum, but please do go through all of the troubleshooting and FAQ documentation first.
