### ISSUE TITLE
Should we rename this thing? Is that a horrible idea or is it necessary?

### ISSUE THREAD

**Issue by jonathanstegall** [MinnPost/object-sync-for-salesforce#53]
I'm wondering because technically, the REST API is different from the other APIs that Salesforce supports, and as this thing grows over time it may support the other APIs. Especially the SOAP one, since the Drupal suite already does this.

Maybe it doesn't matter, but it's at least worth thinking about before it gets submitted to the WP plugin directory.

**Comment by jonathanstegall** [comment]
GitHub will redirect, if we should happen to rename. It's just a question then of whether it makes more sense in a future-compatible and also accuracy sense (even now, the plugin supports a good bit of the Metadata API, which according to Salesforce is distinct.

From https://developer.salesforce.com/page/Salesforce_APIs:

>>>
The following pages provide more information on how to access and use Salesforce APIs:

    REST API - Access objects in your organization using REST.
    SOAP API - Integrate your organization’s data with other applications using SOAP.
    Tooling API - Build custom development tools for Force.com applications. Coming soon!
    Chatter REST API - Access Chatter feeds and social data such as users, groups, followers, and files using REST.
    Bulk API - Load or delete large numbers of records.
    Metadata API - Manage customizations in your org and build tools that manage the metadata model (not the data, itself).
    Streaming API - Provide a stream of data reflecting data changes in your organization.
    Apex REST API	- Build your own REST API in Apex. This API exposes Apex classes as RESTful Web services.
    Apex SOAP API - Create custom SOAP Web services in Apex. This API exposes Apex classes as SOAP Web services.
    Data.com API - Data.com provides 100% complete, high quality data, updated in real-time in the cloud, and with comprehensive coverage worldwide.

**Comment by rclations** [comment]
WordPress has gotten stricter about the usage of brand names in plugins - see # 17 in https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/

From the perspective of WordPress users, we may want to focus the branding on the ability this creates for users to sync their data between WordPress & Salesforce, rather than the specific method (rest api) by which we do that.

Any of these ideas for names (or variations of them) strike your fancy?
>>>
Rest API Sync for Salesforce
Data Object Sync for Salesforce
Two-Way Sync for Salesforce

**Comment by jonathanstegall** [comment]
@rclations that makes sense; I hadn't read that part. My original concern was about the REST API technically not being the only API the plugin supports, even already since it does a bit of work with the Metadata API.

I think maybe Data Object Sync for Salesforce is the best of those. Drupal calls it the Salesforce Suite, but I always thought that was a bit vague anyway. So I don't know that Suite for Salesforce would be any better.

**Comment by jonathanstegall** [comment]
I made a branch for this renaming business. https://github.com/MinnPost/object-sync-for-salesforce/tree/rename-the-plugin

**Comment by jonathanstegall** [comment]
I believe this is all done now.
