### ISSUE TITLE
Not pulling records with large number of contacts and offset calculation error

### ISSUE THREAD

**Issue by HyprCoder** [MinnPost/object-sync-for-salesforce#541]
**Describe the bug**

We are using this plugin on a ecommerce website with lots of contacts which are daily updated on Salesforce. The Salesforce contacts are mapped to Wordpress users, and the plugin is configured to fetch 200 items every 15 minutes. 

We're finding many cases of users with fields not updated. After various tests i found a possible error on how queries to Salesforce are created during the object_sync_for_salesforce_pull_check_records action, specifically in the get_updated_records function.

If i understand correctly the function does the following:

1. It generates the first query to Salesforce and fetches the records. For each record an action is generated if the record can be pulled.
2. It saves the LastModifiedDate of the last item processed in db. Then it executes check_offset_query function.
3. check_offset_query executes a query to Salesforce  by calling get_pull_query function and see if there are additional results. Contacts found by this query **are not pulled**
4. If check_offset_query returns true, a third get_pull_query call is made, this one saves the current_query option on the db with the offset.
5. When the next action starts, the function get_pull_query gets called again. Here the offset gets added again, so another batch of contacts are lost. 

I'm working on a fix for this problem and i will send a PR eventually, but does this makes sense to you?

**To Reproduce**
1. Set the pull query record limit to 2 in the plugin settings, setup a fieldmap  for Users -> Contacts.
2. Create 10 users and push them to Saleforce.
3. Update the mapped contacts on Salesforce
4. Wait or trigger the object_sync_for_salesforce_pull_check_records until the current_query option is deleted.

**Expected behavior**

All 10 users should be updated.

**Current behavior**
Some users don't get updated

**Environment :**
 - WordPress Version: 6.6.2
 - Relevant plugins installed: WooCommerce, Advanced Custom Fields
 - PHP Version 8.3

**Comment by jonathanstegall** [comment]
Thanks for reporting this. No one is currently working on this plugin, but I still have access to it. This does make sense to me as a plausible issue; I used to occasionally see reports of similar issues but was never able to reproduce them. I'd be willing to review a PR if you're able to submit it and, if it works as expected, would merge it.
