### ISSUE TITLE
Admin: admin_notices

### ISSUE THREAD

**Issue by jonathanstegall** [MinnPost/object-sync-for-salesforce#6]
We should think about what kind of admin_notices to use, if any. The codex has [a page](https://codex.wordpress.org/Plugin_API/Action_Reference/admin_notices) about this.

**Comment by jonathanstegall** [comment]
I suppose this is also related to #11.

**Comment by jonathanstegall** [comment]
Reorganized this stuff to make it easier to add new ones in 1d3e6f514d67d3b91a543821d5c30c8c4fa3b102

**Comment by jonathanstegall** [comment]
The way to finish this is to deal with the [`add_settings_error`](https://codex.wordpress.org/Function_Reference/add_settings_error) stuff as part of each tab's settings.

**Comment by jonathanstegall** [comment]
Some links:

- [https://codex.wordpress.org/Function_Reference/add_settings_error](https://codex.wordpress.org/Function_Reference/add_settings_error)
- [https://digwp.com/2016/05/wordpress-admin-notices/](https://digwp.com/2016/05/wordpress-admin-notices/)
- [https://codex.wordpress.org/Plugin_API/Action_Reference/admin_notices](https://codex.wordpress.org/Plugin_API/Action_Reference/admin_notices)

**Comment by benlk** [comment]
Is there a list of conditions that need to be imported into https://github.com/MinnPost/object-sync-for-salesforce/blob/master/classes/admin.php#L799-L812, or general guidelines for finding them?

**Comment by jonathanstegall** [comment]
No, not really. This is just a thought to improve the usability of the admin area. As for a guideline, I'd say if you are clicking around in the admin and you think something should notify you that it happened, that would be awesome.

I would be happy to do some usability testing on this once we have other users in it to identify other conditions, but I've been too far in the weeds for too long to be helpful :)

**Comment by jonathanstegall** [comment]
I figure we'll have to move this one to v2.

**Comment by jonathanstegall** [comment]
I think this is fine, at least unless we learn new information. Certainly there is room to improve usability of the plugin further, but I think probably admin notices are not the place to do it. So shelving it for now.
