### ISSUE TITLE
Convert Grunt to Gulp

### ISSUE THREAD

**Issue by jonathanstegall** [MinnPost/object-sync-for-salesforce#61]
I can't see any reason not to switch, with INN using Gulp.

**Comment by jonathanstegall** [comment]
Started work on this in these commits:

1. 8f3045b954569488349d4d772a5b72657b76d8fa
2. f4da2e287bd541454ff05841238df5ecfafdca16
3. cf18468ecf89ae3263a5675f143f48e4d96147b4

**Comment by rclations** [comment]
setup sass compiling w/ 9a3559de411b459f33c8b9d5e37f17b9c5220020

what else is left here?

**Comment by jonathanstegall** [comment]
I think this is fine now with 504722d610e9f148a71979ee43b7e445f37dc660. I fixed the CSS path, and also added a path I had forgotten for imagemin.

**Comment by jonathanstegall** [comment]
Merged in PR #76
