### ISSUE TITLE
Authorize Tab Returned SF Contacts List

### ISSUE THREAD

**Issue by rclations** [MinnPost/object-sync-for-salesforce#64]
What happens when you load this page using a SF database that's huge? In our testing, we're using pretty low numbers so this seems to work - but what about when you're using a database with 20k contacts?

I'm wondering if we should list the # of contacts and show the first 20, marking them as a "sample" ?

**Comment by jonathanstegall** [comment]
It limits to 100, currently. But I don't mind limiting it further.

**Comment by jonathanstegall** [comment]
Now that I think about it, I think if we mark it as "sample" with like a watermark kind of thing, it might make people think it's not really their data, like it's just placeholder data. They might realize if they looked closely at it, but I figure many people won't.

We could update the summary text though?
