### ISSUE TITLE
Issue Pulling/Pushing Data

### ISSUE THREAD

**Issue by allynbeth** [MinnPost/object-sync-for-salesforce#97]
I'm having trouble getting any data to pull or push from Salesforce. I'm using a developer salesforce account with dummy data and set up a couple field mappings for testing. I've tried mapping a user and a contact and am not seeing any data transferred. The authorization works fine. I've updated the user in both Worpdress and Salesforce to try and trigger an update but haven't seen anything in the logs or queue. Any tips on a basic test I can setup to verify I can pull basic data. I've try setting time frames on the scheduling tab but the queue always says 0.

**Comment by jonathanstegall** [comment]
@allynbeth thanks for reporting this. I've set up a clean WordPress install with this plugin, and will work to see if I can replicate this issue. I'll report back on what happens.

There are a few things that would be helpful, if you could provide them from your install:

1. What are your Log Settings? These are located at `/options-general.php?page=object-sync-salesforce-admin&tab=log_settings` of your WordPress domain
2. If you are able to access your WordPress database directly, could you post a screenshot of the contents of the `wp_object_sync_sf_field_map` and `wp_object_sync_sf_object_map` tables?

My hope is always that syncing issues will reveal themselves in the logs, but I have seen bugs where they only reveal in the database, and it's possible there is another issue as well but this could help me look.

**Comment by jonathanstegall** [comment]
@allynbeth Oh, I've thought of one other thing that is possibly helpful. You mentioned that you mapped user and contact, and then updated the user in both places.

If the user/contact is pre-existing, the plugin will not (by default) catch that it has been updated. I think we've not documented this well, and I think that's something we document, but basically the plugin works with all data that exists after you install it. So if you create a new WordPress user or a new Salesforce contact, and then update it, both those actions (and all future actions on those records) should trigger the plugin.

However is a way to manually, individually map pre-existing users. Go to any user's info inside the WordPress admin - for example, here's a URL that works in mine: `/wp-admin/user-edit.php?user_id=3` and scroll to the bottom. If the object types are mapped, you should see a field that allows you to paste an Salesforce object ID that should be mapped to this user, or push it to Salesforce to create a new record, and then the objects will be mapped.

It's also true that the plugin could perhaps do this in bulk, but that is more complicated.

I don't know enough to tell if that will solve what you are encountering, but it is worth looking into. In any case, I've been unable to replicate the issue you mention in a fresh WordPress install.

**Comment by allynbeth** [comment]
Thanks for the quick response and guidance! Didn't know there was a
Salesforce section for users so that's helpful. I was able to sync a
Wordpress user with a Salesforce user by manually adding the salesforce
external id in the user settings. Previously it said there was an issue
with the external id being 0.

So first I created a new user in Wordpress and saw the following in the
Salesforce section for the user:

[image: Inline image 1]

Then I updated the user and saw the following:

[image: Inline image 2]

Here's a screenshot of the field mapping for reference.

[image: Inline image 3]


If I create a brand new user in Salesforce should it show up in Wordpress
and vice versa automatically? Or do I have to manually add the external id
for it to work? When I added a new user in Salesforce I didn't see anything
show up in Wordpress.

Thanks!



- -

<http://artispassion.com/>ALLYN BETH BROWN
beth@artispassion.com
facebook.com/artispassion
www.artispassion.com

**Comment by jonathanstegall** [comment]
@allynbeth Thanks for this info. I notice the images don't come through, but I can answer some of the questions.

First, yes - if you create a brand new user in Salesforce or in WordPress it should show up in the other system automatically. You shouldn't have to manually add the ID, unless it existed before the plugin was installed.

However I think maybe this issue on your side is because of that message you mention about the external id being 0. This has been an issue we've seen occasionally, although we thought it was fixed and we haven't seen it recently. It's not consistent, but there are (apparently still) cases where a sync will start but not finish, and this leaves an id of 0 in the database and will sometimes stop other syncs from happening.

If you can access the database, you can check the `wp_object_sync_sf_object_map` table, and if you see a row where the `wordpress_id` or `salesforce_id` field have a 0 value, delete it.

If you can't access the database, I think it's probably worth uninstalling and reinstalling the plugin, as it will get rid of that row.

But knowing this issue is still happening, I think, we'll try to build a feature for getting rid of these rows within the WordPress admin, if they occur.

**Comment by jonathanstegall** [comment]
Started a branch for attempting to deal with this issue. https://github.com/MinnPost/object-sync-for-salesforce/tree/97-more-zero-id-occurrences

Still thinking about what exactly to do with it, but that's where we'll do it. Perhaps a troubleshooting tab that shows any zero id rows with the ability to delete them. Totally a bandaid solution, but without a consistent cause emerging that is maybe the best option. Maybe as time goes on a consistent cause will emerge and we'll be able to get rid of it.

**Comment by jonathanstegall** [comment]
A better idea perhaps is this: generate a different ID when a sync starts so it is not always 0. This way rows that fail, whenever they occur, wouldn't stop new ones from being created. For the sake of debugging, we could start them with something useful. Like sfpull_8675309, sfpush_587156. Then that string would get replaced by the correct system ID if it succeeded. If it didn't, a dev could look for rows that started with those prefixes.

**Comment by allynbeth** [comment]
I do have access to the database so I'll look for the row in the meantime. I'll also try deactivating and reactivating the plugin in case that helps. I'm in a local environment right now but will have a dev environment set up this week so I can retest there in case it's an environment issue. Thanks again for the quick responses and help troubleshooting!

Thanks

**Comment by jonathanstegall** [comment]
@allynbeth thanks. I'll work on this issue as well. We'll update the plugin here and in the WP repository if we think we've put in something that better prevents the 0 id rows.

**Comment by jonathanstegall** [comment]
I think the version I've just released, 1.0.5, fixes this issue. I'll leave it open for now to see if you encounter it again, and I think there's still a possible need for some kind of interface that shows sync failures for whatever reason, but at least they should no longer block future syncs.

**Comment by jonathanstegall** [comment]
Going to close this and count it as solved, unless further information comes to light.
